### ISSUE TITLE
Support Event Registration

### ISSUE THREAD

**Issue by antrik** [Project60/org.project60.sepa#107]
In addition to donations, One-Off DD payments are also useful for paying event fees.

This shouldn't require any major extra functionality I hope; however, as the Event Registration pages use different forms than the Contribution pages, we do need some explicit support.

This is actually a show-stopper for some organisations: while donations are often handled through other means, on-line Event registrations through CiviCRM are often a really important use case.

**Comment by systopia** [comment]
As far as I understand, that's exactly what @magnolia61 wants to do now => moved to 1.1

**Comment by systopia** [comment]
This should be supported by version 1.1 now. See, however, https://github.com/Project60/org.project60.sepa/issues/254, https://github.com/Project60/org.project60.sepa/issues/255 and https://github.com/Project60/org.project60.sepa/issues/258
