### ISSUE TITLE
Add channel

### ISSUE THREAD

**Issue by tttp** [Project60/org.project60.sepa#127]
each mandate can be created by a fundraising provider, we need to be able to store that (source as a free form might not be good enough, as an extra contact reference.

**Comment by systopia** [comment]
@tttp We're planning do feature freeze for 1.1 in a week or two. Do you want to have it in 1.1 or can it wait for 1.2?

**Comment by tttp** [comment]
let me check the impact on monday, with the updated master.

X+

**Comment by systopia** [comment]
moved to 1.2 due to lack of time

**Comment by systopia** [comment]
Since AI doesn't need this any more, and no one else ever expressed any interest, I'll close this now.
