### ISSUE TITLE
notices on contrib page

### ISSUE THREAD

**Issue by tttp** [Project60/org.project60.sepa#177]
Fresh install, created a PP sepa (using the pre-defined test creditor)+contribution page allowing recurring contribs, when saving, I get:

```
Notice: Undefined index: account_holder in CRM_Contribute_Form_ContributionBase->assignToTemplate() (line 612 of /var/www/html/sites/all/modules/civicrm/CRM/Contribute/Form/ContributionBase.php).
Notice: Undefined index: bank_identification_number in CRM_Contribute_Form_ContributionBase->assignToTemplate() (line 613 of /var/www/html/sites/all/modules/civicrm/CRM/Contribute/Form/ContributionBase.php).
Notice: Undefined index: bank_name in CRM_Contribute_Form_ContributionBase->assignToTemplate() (line 614 of /var/www/html/sites/all/modules/civicrm/CRM/Contribute/Form/ContributionBase.php).
Notice: Undefined index: bank_account_number in CRM_Contribute_Form_ContributionBase->assignToTemplate() (line 615 of /var/www/html/sites/all/modules/civicrm/CRM/Contribute/Form/ContributionBase.php).
Notice: Undefined index: frequency in CRM_Core_Payment_SDD->doDirectPayment() (line 126 of /var/www/html/sites/all/modules/extensions/sepa_dd/CRM/Core/Payment/SDD.php).
Notice: Undefined index: frequency in CRM_Core_Payment_SDD->doDirectPayment() (line 167 of /var/www/html/sites/all/modules/extensions/sepa_dd/CRM/Core/Payment/SDD.php).
Notice: Undefined index: account_holder in CRM_Contribute_Form_ContributionBase->assignToTemplate() (line 612 of /var/www/html/sites/all/modules/civicrm/CRM/Contribute/Form/ContributionBase.php).
Notice: Undefined index: bank_identification_number in CRM_Contribute_Form_ContributionBase->assignToTemplate() (line 613 of /var/www/html/sites/all/modules/civicrm/CRM/Contribute/Form/ContributionBase.php).
Notice: Undefined index: bank_name in CRM_Contribute_Form_ContributionBase->assignToTemplate() (line 614 of /var/www/html/sites/all/modules/civicrm/CRM/Contribute/Form/ContributionBase.php).
Notice: Undefined index: bank_account_number in CRM_Contribute_Form_ContributionBase->assignToTemplate() (line 615 of /var/www/html/sites/all/modules/civicrm/CRM/Contribute/Form/ContributionBase.php).
Notice: Undefined index: mandate_reference in sepa_pp_buildForm() (line 97 of /var/www/html/sites/all/modules/extensions/sepa_dd/sepa_pp_sdd.php).
```

I reminds me something I fixed on the original PP, but too far away right now.
@nikobo @systopia do you disable php notices on your dev environment?

**Comment by systopia** [comment]
@nikobo Could you please check if this is still the case in current ``master``?

**Comment by nikobo** [comment]
Yes this is, at least partially, still the case. I get the following notices:

>Notice: Undefined index: account_holder in CRM_Contribute_Form_ContributionBase->assignToTemplate() (line 644 of /var/www/html/ff/sites/all/modules/civicrm/CRM/Contribute/Form/ContributionBase.php).
Notice: Undefined index: bank_identification_number in CRM_Contribute_Form_ContributionBase->assignToTemplate() (line 645 of /var/www/html/ff/sites/all/modules/civicrm/CRM/Contribute/Form/ContributionBase.php).
Notice: Undefined index: bank_name in CRM_Contribute_Form_ContributionBase->assignToTemplate() (line 646 of /var/www/html/ff/sites/all/modules/civicrm/CRM/Contribute/Form/ContributionBase.php).
Notice: Undefined index: bank_account_number in CRM_Contribute_Form_ContributionBase->assignToTemplate() (line 647 of /var/www/html/ff/sites/all/modules/civicrm/CRM/Contribute/Form/ContributionBase.php).

**Comment by systopia** [comment]
@nikobo We'll have to reproduce this together, doesn't happen on my end...
