### ISSUE TITLE
With insufficient permissions, 'record SEPA' button not placed correctly

### ISSUE THREAD

**Issue by systopia** [Project60/org.project60.sepa#205]
With certain permissions the contribution tab looks slightly different, and the button cannot be placed in the right spot.

**Comment by systopia** [comment]
This fix somehow got undone, probably with the changes in the contect of https://github.com/Project60/org.project60.sepa/issues/214

**Comment by systopia** [comment]
@nikobo: Could you please verify that this fix also works on CiviCRM 4.5?

**Comment by nikobo** [comment]
@systopia: From my tests it seems that this fix works on CiviCRM 4.5.x, although there is another issue when accessing the contribution tab of a contact with insufficient permissions described [here](#253)
