### ISSUE TITLE
Improve PaymentProcessor

### ISSUE THREAD

**Issue by bjendres** [Project60/org.project60.sepa#215]
Currently, the payment processor is very basic, and there's already a couple of issues raised on this.
In particular, the current implementation does
- not process premiums
- not work well with membership / event pages
- not send out confirmation emails

The reason for this is, that we had to cut off the process after the `doDirectPayment()` call, because the following code messes up the SEPA mandate. We will now try a different approach, details to follow

**Comment by magnolia61** [comment]
Would this new approach be compatible with existing mandates? I mean do the changes affect the proces more than the outcome? And... would you still advise me to try to get the OOFF working from the master branch or your new approach?

**Comment by systopia** [comment]
> Would this new approach be compatible with existing mandates?

Most likely yes. The development focuses on getting rid of a lot of issues we had with the payment process in donation pages (or similar) rather than the resulting mandates - but we'll have to wait until the implementation is complete to answer this question definitively.
