### ISSUE TITLE
Descriptfull debit message in xml

### ISSUE THREAD

**Issue by magnolia61** [Project60/org.project60.sepa#231]
RIght now the contribution message is hardcoded into the xml to say 'thanks'. 
<Ustrd>Thanks.</Ustrd> 
This is very nice and friendly, but not really descriptive. It makes some people question the transaction and make them refund it with extra cost and hassle for our organisations.

Proposed functionality would be very basic but a little different for different sources along these lines:
1) Contribution: <Ustrd>Thank you for contribution. "Campaign name"</Ustrd>
2) Membership:
    new: <Ustrd>New Membership 'Gold'.</Ustrd>
    renewal: <Ustrd>Renewal Memberschip 'Silver'.</Ustrd>
3) Event: <Ustrd>Name of event. [First name participant]</Ustrd>

Any ideas on this? It doesn't have to be admin configurable (although I would love that!), and I believe it does not need extra database fields. Has anyone thought of this before?

**Comment by tttp** [comment]
Hi,

We thought that the degree of what needs to be customised is more complex
than that and possibly specific to each org (eg. having a special msg
around the end of the year if average donation lower than x...)

It's easy to customise via a simple line of code, might be more flexible
for you to create that custom extension so you can define the msg the way
you want for your org. want to try? Would be happy to give you a hand and
use that as example (but needs some php knowledge)


X+

**Comment by magnolia61** [comment]
Hi Xavier,
OK, I'm open to have a try. I am not able to code from scratch, but with some good examples I can expand from that.

Would it be possible for you to write a very basic custom extention that changes the Ustrd field to something else?

This would help me learn and understand the mechanics of the custom extension and help me start to code myself from there.

**Comment by systopia** [comment]
As @tttp implies, this function is -of course- already there. You need to have your customisation extension implement the ```civicrm_modify_txmessage``` hook - as demonstrated in the https://github.com/Project60/sepa_dd/blob/master/README.md

@magnolia61 I offered to talk to you on Skype about this, wouldn't that be a good moment?

**Comment by systopia** [comment]
@magnolia61: I added the example extension, you should find all you need there.

**Comment by antrik** [comment]
We discussed this a couple of times at SfE, and concluded that while some organisations will have complex wishes that should be handled via hooks, it would still be good to have some sane default handling for the rest of us. We will probably implement this sooner or later -- though possibly on the SfE branch, in case it happens before the merge...

Instead of implementig a fixed default logic, we could also implement support for configuring the text with Smarty tokens. This shouldn't be too hard to code, and would provide considerable customisability without resorting to hooks.

**Comment by systopia** [comment]
> Instead of implementig a fixed default logic, we could also implement support for configuring the text with Smarty tokens. This shouldn't be too hard to code, and would provide considerable customisability without resorting to hooks.

Sounds like a good compromise.

**Comment by magnolia61** [comment]
Coming back on this issue, I think I need some advise to code a variable custom message in the customisation extension. I would like to include the display name of the contributor in the message. Can any of you help me with advise on how to retreive and set this info? Tnx!
 
function sepacustom_civicrm_modify_txmessage(&$txmessage, $info, $creditor) {
    $txmessage = "2015 fee for $display_name";
}

**Comment by systopia** [comment]
Something like this (untested) should do the trick:
```
function sepacustom_civicrm_modify_txmessage(&$txmessage, $info, $creditor) {
  $contact_id = $info['contact_id'];
  $contact = civicrm_api('Contact', 'getsingle', array('id' => $contact_id, 'version' => 3));
  if (empty($contact['is_error'])) {
    $display_name = $contact['display_name'];
  } else {
    $display_name = 'Unknown';
  }
  ...
```

**Comment by magnolia61** [comment]
Was nice to meet you at Civicon NW Europe yesterday :-)

The code we end up using to have the display name in the transaction message was the code below. I think in most use cases this would be enough. Event title or membership level would be the other two main options that could be included in a configurable setting (https://github.com/Project60/org.project60.sepa/issues/278).
Maybe the preg_replace I added should go into the main extension after this customization hook to prevent characters that are not allowed ending up in the xml. 

function sepacustom_civicrm_modify_txmessage(&$txmessage, $info, $creditor) {
    $contact_id = $info['contact_id'];
    $contact = civicrm_api('Contact', 'getsingle', array('id' => $contact_id, 'version' => 3));
    if (empty($contact['is_error'])) {
      $display_name = $contact['display_name'];
    } else {
      $display_name = '-';
    }
    $display_name = preg_replace('~&([a-z]{1,2})(acute|cedil|circ|grave|lig|orn|ring|slash|th|tilde|uml);~i', '$1', htmlentities($display_name, ENT_QUOTES, 'UTF-8'));
    $txmessage = "Contribution for ".$display_name;
}

**Comment by systopia** [comment]
> Maybe the preg_replace I added should go into the main extension after this customization hook to prevent characters that are not allowed ending up in the xml. 

Good point. I added this to https://github.com/Project60/org.project60.sepa/issues/278

@magnolia61  I'll close this ticket now, let me know if you disagree...
