### ISSUE TITLE
IBAN & Collection date available as token for emails

### ISSUE THREAD

**Issue by magnolia61** [Project60/org.project60.sepa#240]
A week after registration we send out an automated email to the parents of our camp participant to check the registration information.

We would like to include a section about the direct debit payment in this email.
Would it be very hard to have the IBAN and collection date available as tokens?

Kind regards,
Richard

**Comment by systopia** [comment]
> We would like to include a section about the direct debit payment in this email.
Could you be more specific? How exactly do you want to create the email? Individually? By batch? If a contact has more than one mandate, how would it know which one you want in the email?

In the meantime, we have the ``PDF Prenotification`` button in the mandate to generate a PDF file with this data. That is something that you could then attach to your email.

**Comment by magnolia61** [comment]
We would like tot include it in a scheduled mail tot participants so from the event_id and the uid the corresponding mandate could be found. The same flow would apply to memberships I guess.

**Comment by systopia** [comment]
So, are we talking about the "Scheduled Reminders" system here?

**Comment by magnolia61** [comment]
Yep. Between registration and the even itself we send the parents of oud summercamp participants a series of mails. The first mail would inform on the payment and preferably include the IBAN, amount and collection date as a extra confirmation.

**Comment by tttp** [comment]
For security reason, not sure it's a good idea to multiply the number of
emails with IBAN in it.

Think about it: if you don't require paper mandate, the IBAN is like a
credit card number: it's the only thing needed to buy something online. For
good reasons, you wouldn't send the credit card number by email, shouldn't
it be the same practice for iban?

X+

**Comment by systopia** [comment]
> For security reason, not sure it's a good idea to multiply the number of emails with IBAN in it.

That's a good point. But it should be up to the user to decide this. I think it makes sense to implement this, and to provide the email processor with all the relevant mandate information - whether you use it not.

@magnolia61: I would estimate this to require 2-4hrs, if you help with the testing.

**Comment by magnolia61** [comment]
You know I am glad to help in the way I can: debugging & testing on drupal & joomla in a production setting :-)

**Comment by systopia** [comment]
Sounds good. Then all we need, as the tag ``needs funding`` indicates, is funding.

**Comment by systopia** [comment]
@magnolia61: Please have a look at https://github.com/Project60/org.project60.sepa/issues/250 and tell me if it works now.

**Comment by eptbertram** [comment]
Late answer, but there are some SEPA mandate tokens now (German here, but they shall be in your language as well): 

- {Letztes_SEPA_Mandat.iban} 
- {Letztes_SEPA_Mandat.iban_anonymised} 
- {Letztes_SEPA_Mandat.first_collection} 
- {Letztes_SEPA_Mandat.amount_text} 
- {Letztes_SEPA_Mandat.amount} 
- etc. 

Hope this helps you and anybody else :)

**Comment by bjendres** [comment]
Thanks @eptbertram!
