### ISSUE TITLE
download as org.project60.sepa

### ISSUE THREAD

**Issue by magnolia61** [Project60/org.project60.sepa#241]
Somehow when I clone or download this repository it us always named: sepa_dd instead of org.project60.sepa Can this be changed? The releases have this foldername too :-)

**Comment by systopia** [comment]
This is a legacy, and some early installs would still be using this name. I now always use the ``org.project60.sepa`` identifier. 

You can simply rename your local folder. 

I don't want to rename the whole repository, because it would break a lot of links everywhere. Also, most people (hopefully) will download the official releases rather than "bleeding edge" code.

**Comment by tttp** [comment]
And it works the same no matter the name of the folder ;)

**Comment by antrik** [comment]
Not sure this is relevant, but when cloning with Git on the command line, you can specify the directory name by adding it as the last parameter after the upstream repository name. Or just rename it afterwards :-)

**Comment by nikobo** [comment]
@systopia 
>I don't want to rename the whole repository, because it would break a lot of links everywhere.
There should be no problems as long as there is no repository that uses the 'old' name ("sepa_dd"): https://help.github.com/articles/renaming-a-repository/

**Comment by systopia** [comment]
Thanks, @nikobo.
So, any objections to renaming the repository to ``org.project60.sepa``? @tttp?

**Comment by tttp** [comment]
I'm fine for a rename, we'll just advertise it, and may be add a sepa_dd
that contains as "moved away" msg in a single README

Personally, I prefer sepa (so the folder is shorter) and definitely doesn't
make sense to have sepa_dd that is different than the name of the
extension, but don't care enough about the name to argue either way.
Whatever you want to rename to is fine ;)

**Comment by systopia** [comment]
> I'm fine for a rename, we'll just advertise it, and may be add a sepa_dd that contains as "moved away" msg in a single README 

Did you have a look at @nikobo's [link](https://help.github.com/articles/renaming-a-repository/)? It says that *all* traffic to the old repository name will be automatically redirected.

**Comment by tttp** [comment]
then I'm even more fine ;)

I'm at fosdem, so really shitty internet connection, my apologies, I didn't
read it before replying.

**Comment by systopia** [comment]
> I'm at fosdem, so really shitty internet connection, my apologies, I didn't read it before replying.

Don't worry. I just changed it, and everything seems to be fine. I renamed CiviBanking repo, too.
