### ISSUE TITLE
Permissions

### ISSUE THREAD

**Issue by systopia** [Project60/org.project60.sepa#243]
Version 1.2 will get proper permissions for users / administrators of the SEPA system.

Proposed permissions:
1. **Create SEPA Mandates**  - allows you to create mandates, but don't view or edit them
2. **View SEPA Mandates** - view mandates, no permission to change anything
3. **Edit SEPA Mandates** - allows mandate editing, including endind, cancelling, etc.. This implies "Create Mandates"
4. **Delete SEPA Mandates** - allows the deletion (no ending/cancellation). This should only be allowed to administrators.
5. **View SEPA Groups** - View, but not edit SEPA batching group status. Also allows you to see the associated individual contributions for each group.
6. **Batch SEPA Groups** - General permission for batching/submitting SEPA Groups. Does not allow deletion of groups.
7. **Delete SEPA Groups** - Usually these groups should not be deleted, possible use cases would only be to get rid of old data, and wrongly created ones.

**Comment by DanielvV** [comment]
**4. Delete SEPA Mandates**
If this permission is set, but the _Delete SEPA transaction groups_ permission is unset the Mandate Options -> Delete button is not shown
If this permission is unset, but the _Edit SEPA mandates_ permission is set the mandate_action_delete(); can still be succesfully called from the JS browser console

**Comment by systopia** [comment]
@DanielvV I'll have a look, thanks

**Comment by systopia** [comment]
I'd like to close this general ticket.

@adanielvv: Could you please create a new one for the delete mandate bug?
