### ISSUE TITLE
BIC should not be mandatory

### ISSUE THREAD

**Issue by Detsieber** [Project60/org.project60.sepa#245]
Since 2014-02-01, for payments within one country, only the IBAN is required, while the BIC is optional. From 2016-02-01, this will be the case within the whole SEPA area. However, in the SEPA DD master branch, the BIC is still mandatory.

1) At least for payments within one country, the BIC should not be required anymore.

2) Starting from 2016-02-01, the BIC might be generally omitted.

**Comment by systopia** [comment]
see also: https://github.com/Project60/sepa_dd/issues/209

**Comment by bjendres** [comment]
Will be released with ``1.5``
