### ISSUE TITLE
Normalise IBAN

### ISSUE THREAD

**Issue by magnolia61** [Project60/org.project60.sepa#246]
It would probably be wise & nice to translate all IBAN's to uppercase characters.
I do not know where to change it, but it should be something like strtoupper($IBAN) I guess.

**Comment by systopia** [comment]
Good idea. Ideally we would normalise the whole IBAN, e.g. strip whitespaces, etc.

**Comment by antrik** [comment]
This is a bit unspecific: in what situations should the normalisation take place specifically?

FWIW, in the SfE variant we do this during form processing, along with the IBAN (and BIC) validation; and also in the BAO, to be safe for API calls etc. This is visible in the commits I mentioned in #139.

**Comment by systopia** [comment]
Well, obviously the objective has to be that only one format (the machine one) ends up in the database.

**Comment by antrik** [comment]
I was wondering about places like the (optional) contribution confirmation screen, where it's not in the DB yet.

Admittedly, that's a somewhat minor question -- it does affect the implementation though.

The way we implemented it, it should show in the normalised from on the confirmation screen I think. (Haven't actually tested it...)

**Comment by systopia** [comment]
The API will currently not accept any dashes or white space characters, but it doesn't enforce upper case.

But in any case, the input forms should force the user to only enter normalised IBANs. The payment processor already does that, but the back office form doesn't.

So... two changes:
 1. extend verification to ``[0-9][A-Z]+``
 2. copy input field JS from payment processor to back office form.

**Comment by magnolia61** [comment]
not sure if itś helpfull for any of you but for us it was; some sql code to normalise existing IBAN records:

````
UPDATE civicrm_sdd_mandate SET iban = UPPER(iban);
UPDATE civicrm_sdd_mandate SET iban = REPLACE(`iban`, ' ', '');
````

**Comment by systopia** [comment]
I think https://github.com/Project60/org.project60.sepa/commit/61bc67c41d906af633c85c5201ba3fa0fa28a620 should have fixed this.

@magnolia61: Could you test this please?

**Comment by systopia** [comment]
@nikobo please verify that this works in the current ``master`` and close the ticket

**Comment by nikobo** [comment]
After the latest commit i regard this issue as solved.
