### ISSUE TITLE
Event cancellation does not result in contribution cancellation

### ISSUE THREAD

**Issue by magnolia61** [Project60/org.project60.sepa#247]
We just had out first cancellation of the year :-(
When I tried to handle the administation of that the cancellation of the event participant did not result in cancellation of the corresponding contribution and mandate. Probably these should be related?

**Comment by systopia** [comment]
You're supposed to cancel the mandates (via edit mandate). Maybe there should be a warning when you simply edit the contribution.

**Comment by antrik** [comment]
After careful consideration, we decided that the regular way to cancel SEPA contributions should be cancelling the contribution. No collection is done on cancelled contributions, regardless of the mandate status.

Technically, we still support cancelling the actual mandate too -- but I'm not sure there is an actual use case for that, as long as contributions and mandates are connected 1:1. Perhaps in the (unlikely) case that someone explicitly asks for the mandate to be retracted?

This is somewhat unrelated though to the original point about cancelling the contribution when the event registration is cancelled. I wouldn't say this is something that should be handled by the payment processor, though? Sounds more like an upstream issue for CiviEvent...

**Comment by systopia** [comment]
We need to find a consistent concept here, and prevent the user from accidentally messing it up. And at the same time we don't want to restrict the user's actions too much. We'll tackle this in version 1.2

**Comment by systopia** [comment]
see https://github.com/Project60/org.project60.sepa/issues/286
