### ISSUE TITLE
Sanitize payment processor's IBAN input

### ISSUE THREAD

**Issue by systopia** [Project60/org.project60.sepa#251]
The validation rule for the IBAN form doesn't accept the human readable form if the IBAN, but dismisses it as invalid. In the same way, the automatic lookup using the "Little BIC extension" fails.

**Comment by systopia** [comment]
implemented with https://github.com/Project60/org.project60.sepa/commit/f9715b89fa719179c423723357f61e977a7d2505 and https://github.com/Project60/org.project60.sepa/commit/41b3c05642001fed891f3988e6a750affb543a8b

**Comment by nikobo** [comment]
The whitespace replacement in https://github.com/Project60/org.project60.sepa/blob/f9715b89fa719179c423723357f61e977a7d2505/templates/CRM/Core/Payment/SEPA/SDD.tpl#L161 does not work correctly with Chrome, because only the first occurrence of a (white-)space is removed.
