### ISSUE TITLE
API permission errors

### ISSUE THREAD

**Issue by nikobo** [Project60/org.project60.sepa#253]
When accessing the contribution tab of a contact with insufficient permissions multiple error messages are displayed by the api:

>API permission check failed for SepaMandate/get call; insufficient permission: require administer CiviCRM

This is most likely related to #243

**Comment by systopia** [comment]
Problem confirmed on CiviCRM 4.5.8 with CiviSEPA 1.1

**Comment by systopia** [comment]
It's the SepaMandate.get that is used to inject the mandate link.

**Comment by systopia** [comment]
fixed in ``1.2.x``. Won't fix for ``master`` (1.3) because of ticket #243

**Comment by systopia** [comment]
fixed with https://github.com/Project60/org.project60.sepa/commit/cc3f767c6ce8ba8e87d75ccb8a0e1593eabf7d6d
