### ISSUE TITLE
Delete a cancelled mandate / contribution

### ISSUE THREAD

**Issue by magnolia61** [Project60/org.project60.sepa#255]
There is currently no way to delete a cancelled mandate and/or the corresponding contribution.

 1. I canceled the mandate of an event registration
 2. Both the mandate and the corresponding contribution now have the status cancelled.
 3. There is no way to delete the mandate (no button)
 4. There is no way to delete the contribution (it throws an ugly full screen error I should first delete the mandate)

I assume (and hope) this not expected behavior :-)

![civicrm_sepa_deletecancelledmandate](https://cloud.githubusercontent.com/assets/2195908/6190179/69b956b0-b3a0-11e4-9a8d-11b87efe6c15.png)

**Comment by systopia** [comment]
> There is no way to delete the mandate (no button)
> There is no way to delete the contribution

This is intended, since you should keep a record of any transaction that you submitted to the bank. If you delete every trace of it, how will you be able to answer to the bank or your customer?

**Comment by magnolia61** [comment]
I our case the transaction was not submitted to the bank yet (group was not closed yet).
One parent of a participant of our summercamps contacted us and wants to pay by bank instead.

What workflow would you advise for this? Should we cancel the mandate? Cancel the contribution? Record a new contribution against the event? (I don't know how to do that).

**Comment by systopia** [comment]
> I our case the transaction was not submitted to the bank yet (group was not closed yet).

In this case you should be able to delete the mandate (with Administrator privileges, see also https://github.com/Project60/org.project60.sepa/issues/243).

**Comment by systopia** [comment]
I'll close this now, please re-open if you feel that it's not adequately answered...
