### ISSUE TITLE
Uppercase IBAN and BIC

### ISSUE THREAD

**Issue by systopia** [Project60/org.project60.sepa#256]
It's currently possible, to enter lowercase BICs and IBANs via the payment processor interface. This needs to change. Also, the JS IBAN formatter should also put everything into uppercase.

**Comment by magnolia61** [comment]
Should the code Niko added be removed now this is fixed? https://github.com/Project60/org.project60.sepa/commit/f78fd980affce5370d6822e87403e196c60588f0
 if (preg_match("/[\s\-]/", $iban)) {
      return ts("IBAN is not correct");
    }

**Comment by systopia** [comment]
Good point, but no. We only want "machine formatted" IBANs in the system, so it can't hurt to check for it (again). I updated the comment, though: debd0fa487ab4381f80bb7c303bfa9d146fe5f83

**Comment by magnolia61** [comment]
Thanks, but I think the form field should allow whitespaces, remove those, validate the IBAN and store in uppercase. It is user-unfriendly to bother them and force them to possibly re-type their IBAN several times when it is clearly an OK number and can be sanitized in the backend.
So I would vote for Niko's check to be removed since we have a beautiful and proper mechanism now :-)

**Comment by systopia** [comment]
There's JS code in place for the payment processor form to do exactly what you ask for. Or am I missing something here?

**Comment by magnolia61** [comment]
maybe I read Niko's code not correctly, but as I understand it now when an end-user submits the form with an IBAN with whitespaces in it he or she will get the IBAN is not correct error. Or do you mean it will get corrected 'in-place' by the javascript?

**Comment by systopia** [comment]
> Or do you mean it will get corrected 'in-place' by the javascript?
Yes, that's what I mean

**Comment by magnolia61** [comment]
Nice :-)
BTW. Is there a sanitazion mechanism active now for the xml-exports?
And/or would you know a way to sanitize the IBAN's currently in our DB?

**Comment by systopia** [comment]
> BTW. Is there a sanitazion mechanism active now for the xml-exports?

No, because we want to keep only sane data in the DB.

> And/or would you know a way to sanitize the IBAN's currently in our DB?

Only manual SQL, sorry. If you want a "button" for it, create a new issue - be we currently don't have any customers to fund such a thing.

**Comment by magnolia61** [comment]
OK, I understand. Thanks.
