### ISSUE TITLE
4.6 readyness

### ISSUE THREAD

**Issue by magnolia61** [Project60/org.project60.sepa#257]
With the 4.6 in beta since today i was wondering, do you foresee any issues with compatibility (or would you think this extension will have no big issues working in 4.6? Of course I will also try and test myself, but you know the architecture of the extension and changes in civicrm better than I do :-)

**Comment by systopia** [comment]
@magnolia61 We currently don't have time/funding to do 4.6 compatibility. Just give it a try, and let us know your findings.

**Comment by tttp** [comment]
@magnolia61 did you test on 4.6?

**Comment by magnolia61** [comment]
Yep, I am testing the latest code with civicrm 4.6.2 right now. Backend functions seem to work ok.
The only thing so far I run into is a regression of the empty hidden start_date field (https://github.com/Project60/org.project60.sepa/issues/223). @nikobo fixed that for 4.5 but maybe it that fix is not compatible with 4.6. I have no clue why that issue returned.

**Comment by magnolia61** [comment]
For 4.6 compatibility the work Eileen has done on payment processor integration would seem very interesting. See https://issues.civicrm.org/jira/browse/CRM-15555
Tips from Eileen: 
Your payment processor should override things like supportsBackOffice to declare whether it should show as an option on the backoffice form.
ValidatePaymentInstrument overrides form validation - ideally you should be able to implement it without using hooks now & if you are still using hooks we should ensure we have the things requiring the use of hooks on our road map

**Comment by antrik** [comment]
On Thu, Apr 30, 2015 at 05:34:59AM -0700, Richard van Oosterhout wrote:
> For 4.6 compatibility the work Eileen has done on payment processor integration would seem very interesting.

This is very relevant for the SfE variant of the SEPA extension, as we are actually using the upstream back-office forms, and will hopefully need considerably less hacks now.

The systopia/project60 variant OTOH shouldn't be affected AIUI, as it implements its own backoffice forms.

**Comment by magnolia61** [comment]
I dream and hope there can be a renewed effort to integrate both variants towards one common release with the best of both worlds because it seems so much energy could be synergy here... </offtopic>

**Comment by systopia** [comment]
> I dream and hope there can be a renewed effort to integrate both variants towards one common release with the best of both worlds because it seems so much energy could be synergy here... #offtopic

I agree, but the merge would be pretty complex, and there is simply no funding for this atm.

**Comment by magnolia61** [comment]
Not sure if this is relevant but thought these recent changes to the 4.6 branch might impact civisepa. FYI: "The fix uses contribution->receipt_date for dating the financial transaction. The correct date to use, I believe, would be contribution->receive_date." https://issues.civicrm.org/jira/browse/CRM-16440

**Comment by systopia** [comment]
step by step: https://github.com/Project60/org.project60.sepa/pull/273
