### ISSUE TITLE
Contribution status workflow?

### ISSUE THREAD

**Issue by magnolia61** [Project60/org.project60.sepa#259]
I believe it would be helpfull to change the workflow of the contribution statusses to the following:

1) initial transaction (donation, membership, event registration)
    contribution gets status: 'pending'
2) groups gets closed, the xml-file is submitted to the bank
    contribution gets status: 'progress'
3) bank reports back with direct debit processing status
    - some failed transactions are first manually set to 'pending' + we clone the mandate 
    - for the rest the contribution gets status: 'completed' (by button in civisepa dashboard)

In this way the status of the contribution is very clear and the work to handle failed contributions is very limited :-)

**Comment by magnolia61** [comment]
An aditional benefit would be that this would allow for better handling of changing of price-sets before submission to the bank.
For 'partially paid' and 'pending refund' changes to the contribution, in the work-flow above it would be clear that the direct debit (civisepa or other), is not 'in progress' yet, so the amount can be changed (on customer request) before we send the xml to the bank.

**Comment by systopia** [comment]
@magnolia61: To my understanding that's exactly how it works right now, with one exception: The report from the banks differs greatly from country to country (and even from bank to bank). In Germany, for example, we don't get a dedicated "direct debit processing status" - the failed transactions simply get deducted from your bank account. Therefore the 'failed transaction' process is currently manual.

If someone has too many failed transactions to handle them manually, I would suggest [CiviBanking](https://github.com/Project60/org.project60.banking). But that still needs some time and expertise to set up...

**Comment by tttp** [comment]
@magnolia61 @systopia

indeed, the sepa standard doesn't include to my knowledge how the bank is
going to give you a list of the rejected/accepted DD... and each bank seems
to be quite creative on what format they provide.

On a not too distant future, we'll probably need to process automatically
sepa. the matcher is likely to be fairly common (ie. you will always have
the transaction id or mandate id) but the file parser is likely to be
something that need to be written for each bank

**Comment by antrik** [comment]
Actually, the Rulebook kinda somewhat prescribes 'camt' (also part of ISO 20022 like 'pain') as the standard format(s) for account statements; however it's not entirely clear how they are supposed to be used exactly. What's more, just like all the "Customer to Bank" formats, these are not strictly mandatory, but only "strongly recommended" -- i.e. (just like with 'pain') the banks can pretty much do what they want. Hurray for "standards".
