### ISSUE TITLE
Financial item status of pending SEPA payment

### ISSUE THREAD

**Issue by magnolia61** [Project60/org.project60.sepa#261]
When dealing with changing price sets I ran into a discussion on the various contribution and line item statuses (See: https://issues.civicrm.org/jira/browse/CRM-16038).
Making changes to the price set before the group is closed and payments are committed to the bank runs into problems by what seems to be an error in the recorded status of the financial item. 

> _David Greenberg commented: Richard - I think the status on the financial_item rows could be the problem. I would expect it to be '3' (unpaid) rather than '1' (paid) for Pending event registrations. This is what happens when using the core 'Pay Later' feature._
> _I would also NOT expect the participant status to be Registered but rather to use the existing 'Pending from pay later' status - since indeed that payment hasn't yet happened. However I'm not sure if that is causing a problem or not._

After a SEPA transaction (for an event registration) I the following is recorded in the database.
'''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''
**civicrm-contribution:**
id = 2328
payment_instrument_id = 14
total amount = 140
is_pay_later = 0
adress_id = 2565

**civicrm_financial_trxn**
id = 4033
total_amount = 140
status_id = 1
payment_processor_id = 40
payment_instrument_id = 1
'''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''
**civicrm_financial_item (1st of 2)**
contact_id = 2169
amount = 145
financial_account_id = 4
status_id = 1
entity_id = 5413

**civicrm_financial_item (2nd of 2)**
contact_id = 2169
amount = -5
financial_account_id = 16
status_id = 1
entity_id = 5414
'''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''
**civicrm_line_item (1st of 2)**
entity_id = 1868
contribution_id = 2328
price_field_id = 7
financial_type_id = 4

**civicrm_line_item (2nd of 2)**
entity_id = 1868
contribution_id = 2328
price_field_id = 11
financial_type_id = 10
'''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''
**payment_processor_type**
id = 25
name = SEPA_Direct_Debit
billing_mode = 1
payment_type = 0

**payment_processor**
id = 40
payment_processor_type_id = 25
billing_mode = 1
payment_type = 2 
'''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''
Summary: (Related issue: https://github.com/Project60/org.project60.sepa/issues/259).
**After registration for a membership or event**
- the participant status should be 'pending from pay later'.
- the contribution status should be 'pending'
- the financial line item should have status '3' (unpaid)

**After submission to the bank**
- the contribution gets status 'progress'

**After bank reports back with processing status**
- the event or membership registration gets status 'registered'
- the contribution gets status 'completed'
- the financial line item gets status '1' (paid)

**Comment by systopia** [comment]
@magnolia61: Thanks for reporting. Unfortunately, we currently don't have funding for tackling this. Contact me, if you want to talk about this.

**Comment by magnolia61** [comment]
Unfortunately we have no financial resources for funding. But we have time to test.
More fundamentally and even before any line is coded: Is David correct in his assumption?
Should the financial line item of the direct debit payment initially be 3 (unpaid) ?

**Comment by magnolia61** [comment]
Just found out what I believe is another bug. Which is in fact already visible in the table above.
The record in the civicrm_financial_trxn sets the payment_instrument to 1 which is Credit Card. This should be ẗhe value for SEPA DD One-off Transaction (in every installation this might be another value, but fr sure it should not be 1 here)

**Comment by magnolia61** [comment]
I am trying to get some broader support for direct debit handling in core civicrm. The GSOC on refunds might be a factor. But also the changes Eileen recently made in 4.6 with allow for greater flexibility. 
My topic and issue on changing selections of the price set for a direct debit payment with civisepa can be found here: http://forum.civicrm.org/index.php/topic,36408.0.html

**Comment by systopia** [comment]
see https://github.com/Project60/org.project60.sepa/issues/286

**Comment by magnolia61** [comment]
Bjorn, I also retested this issue with a regular Contribution Page (instead of an event context).
In this case the status in civicrm_financial_item also gets the status 1 (paid) instead of 3 (unpaid). 
![20150907 financial_item_status](https://cloud.githubusercontent.com/assets/2195908/9719014/ea1582fc-5580-11e5-860b-1c1c6400ca8c.jpg)
The status for the financial_item should be 1 until the payment is marked received.
So, I believe this is not limited to events, but a general issue for civisepa.
