### ISSUE TITLE
Navigation menu item for CiviSEPA settings

### ISSUE THREAD

**Issue by sebastian-leidig** [Project60/org.project60.sepa#262]
During initial setup I was searching for a long time to find the settings screen where I can create a creditor. This doesn't seem to be anywhere in the CiviCRM navigation menu (dropdown). Only later I accidentally I found the link listed on the "Administration Console" page (.../civicrm/admin).

I would propose to add a link to "CiviSEPA Settings" (.../civicrm/admin/setting/sepa) under "Administer | CiviContribute". Or was this purposely left out of the navigation menu? What do you think?

I can make a pull request with the added code if we agree on this.

**Comment by tttp** [comment]
I think it would make sense indeed (just had a customer that didn't find it either)

PR welcome ;)

**Comment by systopia** [comment]
I have no problem with this, go ahead and create a PR :)

**Comment by systopia** [comment]
Thanks for the PR. I added some cleanup  (i.e. moved the utility function, see https://github.com/Project60/org.project60.sepa/commit/ac8b765a562d1faf8a1b7826303362fa0eaeea2a) and some error handling.
@sebastian-leidig Could you please confirm that it works for you and close the ticket?

**Comment by sebastian-leidig** [comment]
works fine, thanks :)
