### ISSUE TITLE
Invalid Campaign order on drop down

### ISSUE THREAD

**Issue by MyriamVanB** [Project60/org.project60.sepa#263]
When creating a new mandate, the list of campaigns is not in the right order.

**Comment by tttp** [comment]
(I'm in @MyriamVanB office) 
It seems to be that the list is ordered by campaign id instead of campaign name.

**Comment by systopia** [comment]
They are not ordered at all, they are displayed in the same order they are replied by the API. How would you like to order it? Alphabetically?

**Comment by tttp** [comment]
alpha on the name indeed (like the other drop down lists of campaigns in other parts of civi).

**Comment by systopia** [comment]
By 'name' you mean the ```title``` attribute, correct?

**Comment by MyriamVanB** [comment]
yes, that's right ...., 

thanks


________________________________________________________

Myriam Van Bavel
Verantwoordelijke Databeheer

Amnesty International Vlaanderen vzw   
Kerkstraat 156 - B-2060 Antwerpen      
T +32 3 271 16 16
T direct +32 3 217 44 28
F +32 3 235 78 12
W www.aivl.be	

Niet aanwezig op vrijdag.

Volg ons:        

This email and any files transmitted with it are confidential and intended 
solely for the use of the individual or entity to whom they are addressed. If 
you have received this email in error please notify the system manager.

**Comment by systopia** [comment]
@tttp Could you check if https://github.com/Project60/org.project60.sepa/commit/4d23434207c01a7d1120ae808c37b584aac2e665 fixes this?

**Comment by systopia** [comment]
Apparently, it works now.
