### ISSUE TITLE
"Mark as received" does not show 

### ISSUE THREAD

**Issue by magnolia61** [Project60/org.project60.sepa#266]
We have some groups that are closed where we do not get the option "mark as received". What would be possible causes and what can we do to fix this? (We would like to mark the contributions as received).
![civisepa_mark-as-received](https://cloud.githubusercontent.com/assets/2195908/7334089/ece8413a-eb87-11e4-898c-f3fa2eb0e9b0.jpg)

**Comment by systopia** [comment]
The "mark as received" button only appears after the collection date.
