### ISSUE TITLE
Fatal error: Call to a member function getVar() on a non-object (SDD.php on line 155)

### ISSUE THREAD

**Issue by magnolia61** [Project60/org.project60.sepa#267]
Trying out this extension on the current stable version 4.6.2 after confirming the contribution I get a white screen with the following fatal error:
Fatal error: Call to a member function getVar() on a non-object in /home/ozk/domains/onvergetelijk.nl/public_html/crm/sites/all/modules/civicrm_extensions/org.project60.sepa/CRM/Core/Payment/SDD.php on line 155

In SDD.php line 155 is:
$params['contact_id']    = $this->getForm()->getVar('_contactID');

Would this point to a small change in how 4.6 deals with contact_id's?

**Comment by systopia** [comment]
> Would this point to a small change in how 4.6 deals with contact_id's?

Sure sounds like it. We'll look into this, when we do 4.6 compatibility (https://github.com/Project60/org.project60.sepa/issues/257)

**Comment by magnolia61** [comment]
Changing the line
$params['contact_id'] = $this->getForm()->getVar('_contactID');
to
$params['contact_id'] = $params['contactID']
solved this issue.
This solution was already referenced in https://github.com/Project60/org.project60.sepa/issues/208 but Iḿ not sure what other impact this change might have.

**Comment by magnolia61** [comment]
https://github.com/Project60/org.project60.sepa/pull/270

**Comment by systopia** [comment]
@magnolia61: This needs to be working on 4.4, 4.5 and 4.6, so we can't simply merge #270.
I'll create a fix based on @tttp's approach when we look into #257

**Comment by systopia** [comment]
@nikobo Did one of your recent modifications affect this?

**Comment by nikobo** [comment]
Yes, apparently [this line](https://github.com/Project60/org.project60.sepa/blob/d86c2e50b5cc228b1c2fb68f7e41370054725587/CRM/Core/Payment/SDD.php#L155) got overwritten with one of the more recent changes. I removed the "getForm()"-call.

**Comment by systopia** [comment]
@magnolia61: Could you please verify that this is working for you now?

**Comment by magnolia61** [comment]
Changing the line
$params['contact_id'] = $this->getForm()->getVar('_contactID');
to
$params['contact_id'] = $params['contactID']
worked for us.

**Comment by systopia** [comment]
Yes, but Niko changed it to
```
$this->getVar('_contactID');
```
which worked for us.

If you have the time, could you test with the latest master?

**Comment by magnolia61** [comment]
works perfectly with current master code and civicrm 4.6.3 Just tested an event registration with this code. 
````
$this->getVar('_contactID');
````

**Comment by systopia** [comment]
Great, thank you! 

Then I'll close the ticket.
