### ISSUE TITLE
cosmetic header issue - event thank you screen + fix

### ISSUE THREAD

**Issue by magnolia61** [Project60/org.project60.sepa#268]
The event Thank You screen layout has a little flaw.
Solution change in templates/CRM/Event/Form/RegistrationThankYou.sepa.tpl:
<h2>{ts}Direct Debit Payment{/ts}</h2>
to:
<div class="header-dark">{ts}Direct Debit Payment{/ts}</div>

![civicrm-sepa_thankyouheader](https://cloud.githubusercontent.com/assets/2195908/7410379/8dda822a-ef2e-11e4-9b53-1e628003683b.png)

**Comment by magnolia61** [comment]
https://github.com/Project60/org.project60.sepa/pull/269

**Comment by systopia** [comment]
Thanks @magnolia61
