### ISSUE TITLE
Can't create your own mandate reference when adding manually

### ISSUE THREAD

**Issue by tttp** [Project60/org.project60.sepa#271]
We have a team getting the mandates on paper, so the number is pre-printed. When we add them, we need to be able to input it instead of the generated reference

@systopia, I think it makes sense as a default (ie. Add a new reference non mandatory field, if empty generate one). Opinion?

**Comment by ErikHommel** [comment]
Check http://civicrm.stackexchange.com/questions/2193/need-to-create-a-sepamandate-for-street-walkers

**Comment by systopia** [comment]
@tttp sounds good. 

In the next couple of days I'm going to look into the release planning for version 1.2, let's talk about it then.

**Comment by systopia** [comment]
ready for testing

**Comment by systopia** [comment]
positive feedback from testing, closing ticket
