### ISSUE TITLE
{$sepa.reference} in E-Mail Template

### ISSUE THREAD

**Issue by oligoform** [Project60/org.project60.sepa#272]
How can i get the {$sepa.reference} in an Mass-E-Mail-Template for notification of the contacts/members?
Best would be, if this {$sepa.reference} and the {$sepa.iban} & {$sepa.bic} are accessible/viewable inside the member-account-view, too.
Another possibility is to export the members data including {$sepa.reference} as an .csv. How to do it?

**Comment by systopia** [comment]
Right now, these smarty variables are only available in the prenotification generator - as you've probably seen. There's also some smarty variables injected into the ``contribution_receipts_online`` mail generated by the payment processor.

If you want to make them accessible as tokens for PDFs and mailings, you'll first have to answer the following question: *Which* of the (potentially multiple) mandates of the contact do you want the system to put there? Since the contact ID is the only context you have in those cases, I don't think there's a good solution to this.

**Comment by oligoform** [comment]
"If you want to make them accessible as tokens for PDFs and mailings, you'll first have to answer the following question: Which of the (potentially multiple) mandates of the contact do you want the system to put there? Since the contact ID is the only context you have in those cases, I don't think there's a good solution to this."

maybe a list of all mandates of the contact?

how can i start to get the variables into the mailings? which files i´ve to check? would you be so kind to give me a hint?

**Comment by systopia** [comment]
> maybe a list of all mandates of the contact?

Still - how would your template figure out which to select?

Anyway, if you want to look into this you'd want to have a look at the [CiviCRM Hook Reference](https://wiki.civicrm.org/confluence/display/CRMDOC/Hook+Reference), in particular the ``hook_civicrm_tokens`` and the ``hook_civicrm_tokenValues`` hooks.

**Comment by oligoform** [comment]
in the PDF-template there are these variables e.g. {$sepa.reference} already accessible. 
is it possible to use this logic?

**i´ll check your link. thank you!**

**Comment by oligoform** [comment]
i´ve found the great API-Explorer: ~/wp-admin/admin.php?page=CiviCRM&q=civicrm%2Fapi%2Fexplorer&reset=1#explorer
now fiddling with this for better understanding

**Comment by oligoform** [comment]
ok, so we went another way. we generate the Mandate both outside and inside CiviCRM with the same logic. your example sepacustom was helpful there. thank you!

**Comment by systopia** [comment]
Great to hear that.

Loosely related: we'll probably add an input field for a manually entered mandate reference to the back office 'create mandate' form in the next relase , see https://github.com/Project60/org.project60.sepa/issues/271
