### ISSUE TITLE
No Contact Name displayed for email only contacts

### ISSUE THREAD

**Issue by Fabian-SYSTOPIA** [Project60/org.project60.sepa#275]
After creating a ooff mandate via a contribution page, no contact name is displayed both in the view of the mandate (civicrm/sepa/xmandate?mid=xx) and the SEPA transaction group contributions view (/civicrm/sepa/listgroup?group_id=xx).

When viewing the mandate I also get the error message "Cannot read contact [Array]. Error was: 'Expected one Contact but found 8'" - however I am not sure if this is related.

**Comment by systopia** [comment]
I strongly suspect this has to do with https://github.com/Project60/org.project60.sepa/issues/281. Usually you should not be able to create creditors/mandates without contact.

@Fabian-SYSTOPIA Please try to reproduce after Niko has fixed https://github.com/Project60/org.project60.sepa/issues/281

**Comment by Fabian-SYSTOPIA** [comment]
I did some tests in CiviCRM 4.6.4. I do not get any more errors, however, there still seems to be a problem with the display name if only email-adresses are provided when making the online contribution. 

If no first or last name is provided, no names are displayed in the dashboard or mandate. In a standard CiviCRM contact view, the correct display name (only email-address) is displayed. After adding a name to an email only contact, dashboard and mandate display works fine. Also, if a name is provided on the contriution page, everything looks fine.

Not sure if the problem is with CiviSEPA or CiviCRM's handling of display names...

**Comment by systopia** [comment]
Last problem fixed with https://github.com/Project60/org.project60.sepa/commit/4be911ed3e3a1f3a651bfe597c000714ff5ea384
