### ISSUE TITLE
Translations with domain

### ISSUE THREAD

**Issue by rubofvil** [Project60/org.project60.sepa#277]
Will be great if the function translations (ts) have the domain of the extension to make more easy the translation maintenance.

For tpls it's easy with 
find . -not \( -path ./.git \) -type f -exec sed -i "s/{ts}/{ts domain='org.project60.sepa'}/" {} +

For "ts(" need more work  :'(
ts('...') => ts('...', array( 'domain' => 'org.project60.sepa'))

http://wiki.civicrm.org/confluence/display/CRMDOC/Extension+translation#Extensiontranslation-Fordevelopers

**Comment by systopia** [comment]
@rubofvil Thanks for the information. We'll apply that in one of the next releases

**Comment by systopia** [comment]
merged to ``1.2.x``

**Comment by systopia** [comment]
merged to ``master`` and released with 1.2.2
