### ISSUE TITLE
Exclude week-ends

### ISSUE THREAD

**Issue by systopia** [Project60/org.project60.sepa#279]
Currently, the any collection day will be accepted. In order to take bank holidays into account, you are supposed to implement the ``civicrm_defer_collection_date`` hook.

For a simple SEPA scenario, however, it might be handy to have a checkbox setting (per creditor) ``defer weekend collection dates``, that would automatically adjust the collection dates to avoid weekends.

A general setting where you could upload the specific bank holidays of your bank would also be good, but is far more work.

**Comment by systopia** [comment]
moved to 1.3 due to lack of funding

**Comment by systopia** [comment]
We've decided to implement this without having funding. It's just too important for small users.

**Comment by systopia** [comment]
@nikobo please verify that this works in the current ``master`` and close the ticket

**Comment by nikobo** [comment]
Seems to be working flawlessly.
