### ISSUE TITLE
'edit mandate' link update missing

### ISSUE THREAD

**Issue by systopia** [Project60/org.project60.sepa#280]
If you go to the contact summary's contribution tab, the links to edit/view a recurring contribution should be changed to 'edit mandate'.

This does currently not work when there is no contributions (section above).

Observed on 4.6.3, but possibly also affects 4.4/4.5

**Comment by systopia** [comment]
@nikobo could you have a look?

**Comment by systopia** [comment]
@nikobo Please test this solution with 4.4, 4.5 and 4.6, each with the three scenarios ("contribution / no recurring", "no contribution, recurring" and "no contribution, no recurring")

**Comment by nikobo** [comment]
4.4 - working
4.5 - working
4.6 - working

I'll close this ticket now.
