### ISSUE TITLE
Question: change participant status after 'mark received' of conctributions

### ISSUE THREAD

**Issue by magnolia61** [Project60/org.project60.sepa#283]
ehm.. just wondering how to do this.
We just marked a transaction group received, thus changing the contribution status to 'completed'.
I cannot figure out a way to now change the participant status for this group.

Ideally at first the participant status would be: Pending from incomplete transaction
and after marking the batch as received we would be able to change it to: registered

**Comment by systopia** [comment]
see https://github.com/Project60/org.project60.sepa/issues/286
