### ISSUE TITLE
Use payment processor for event registrations

### ISSUE THREAD

**Issue by bjendres** [Project60/org.project60.sepa#286]
Evidently (see associated tickets), there is still some issues when using the payment processor for event registration pages. This needs to be tackled in one go, but that would also require some funding.

**Comment by magnolia61** [comment]
Good to cluster these. Unfortunately we can offer no funding but we can offer our time to bugtrace and test and are glad to be able to hep out that way! https://github.com/Project60/org.project60.sepa/issues/261 seems to me not event related but a fundamental question on the design.
