### ISSUE TITLE
Something sneaked through the IBAN filter

### ISSUE THREAD

**Issue by magnolia61** [Project60/org.project60.sepa#292]
We tried to submit another batch and found out the xml would not validate with the bank.
Turns out a strange entry got trough the IBAN validation.

IBAN:NL91ABNA0417164300

The person entered IBAN: in front of the bank account code and somehow it passed validation of the form.

**Comment by systopia** [comment]
Confirmed, this should not be possible.

**Comment by systopia** [comment]
This should have also been fixed by https://github.com/Project60/org.project60.sepa/issues/246 and the pending fix.

@magnolia61: Could you please verify that it works?

**Comment by systopia** [comment]
@nikobo please test and close

**Comment by nikobo** [comment]
This issue does not appear in any of the tested versions. I consider it fixed.
