### ISSUE TITLE
Safari doesn't download xml

### ISSUE THREAD

**Issue by mielert** [Project60/org.project60.sepa#308]
When clicking to download the xml at /civicrm/sepa/dashboard Safari just opens the xml. 
Probably there's something wrong with he headers.

This normally works for me quite well:
header('Content-Transfer-Encoding: binary');  // For Gecko browsers mainly
header('Last-Modified: ' . gmdate('D, d M Y H:i:s', filemtime($filename)) . ' GMT');
header('Accept-Ranges: bytes');  // For download resume
header('Content-Length: ' . filesize($filename));  // File size
header('Content-Encoding: none');
header('Content-Type: application/xml');  // Change this mime type if the file is not PDF
header('Content-Disposition: attachment; filename=' . $filename);  // Make the browser display the Save As dialog

**Comment by systopia** [comment]
We use the ``download`` attribute in the link: 
  ``<a href="{$file_link}" download="{$file_name}">{$file_name}</a>``
Is there any reason why this wouldn't work on Safari?

If not we could add some of the headers you proposed here: https://github.com/Project60/org.project60.sepa/blob/master/CRM/Sepa/Page/SepaFile.php#L35

@mielert: Could you check the ``download`` attribute? Could you create a PR for the new headers? Alternatively: Would you be able to test and verify the changes for both Safari and Firefox?
