### ISSUE TITLE
Button to send an e-mail or PDF with reference

### ISSUE THREAD

**Issue by mielert** [Project60/org.project60.sepa#311]
I get signed, analog forms with new mandates.
So before caching I've got to send the references to new contacts.
In the past I had a hard coded logic: if reference is not send via email or mail the mandate is not active.
Probably we could use INIT for that.

online mandate
-> send out PDF with reference
-> state = INIT
-> get signed mandate
-> state = FRST

offline mandate
-> import offline mandate
-> state = INIT
-> send out email or PDF with reference
-> state = FRST

**Comment by systopia** [comment]
Most of this already exists, except for (https://github.com/Project60/org.project60.sepa/issues/315). With that the workflow would be:
 1. mandate is created, but not active
 2. you use the "prenotification" button to create a PDF
 3. you send that (via email or mail) to your donor.
 4. when you get it back, you use the "activate mandate" option to start collecting the money

@mielert Is that what you had in mind?

**Comment by systopia** [comment]
After a brief chat, https://github.com/Project60/org.project60.sepa/issues/316 is more likely the solution to this question. Depending on the workflow, https://github.com/Project60/org.project60.sepa/issues/315 would be required as well...
