### ISSUE TITLE
Incorrect convention of names for Sepa/DAO files and classes

### ISSUE THREAD

**Issue by scardinius** [Project60/org.project60.sepa#317]
Incorrect convention of names involves problems with API.

Instead of:
`\CRM\Sepa\DAO\SEPAMandate.php`
better use, according to CiviCRM convention:
`\CRM\Sepa\DAO\SepaMandate.php`

The same for class names: `CRM_Sepa_DAO_SEPAMandate` vs. `CRM_Sepa_DAO_SepaMandate`.

Then we can remove workaround [sepa.php:403](https://github.com/Project60/org.project60.sepa/blob/master/sepa.php#L403).

What do you think? It's possible that I can clarify the code.

**Comment by tttp** [comment]
Hi,

@scardinius, kindof agree, but "Sepa" looks as good a "Vat", ie. really weird ;)

Most of the extensions/migration code should be using the api, so _shouldn't_ have too much impact, but that's the kind of change for a main version upgrade+add a note in the release/upgrade.

**Comment by systopia** [comment]
@tttp 1.2 is in beta test, no way! Could you create a dev branch for 1.3 and a PR? I could then run the test suite and see if it's ok

**Comment by bjendres** [comment]
This was fixed with #616 / #615
