### ISSUE TITLE
complain table doesn't exists

### ISSUE THREAD

**Issue by enboig** [Project60/org.project60.sepa#318]
I have dona clean install of civicrm 4.6.8 and downloaded the latest version this module. When I try to create a SEPA file it complains:

    Aug 28 11:05:19  [info] $backTrace = #0 /var/www/html/civicrm/sites/all/modules/civicrm/CRM/Core/Error.php(897): CRM_Core_Error::backtrace("backTrace", TRUE)
    #1 [internal function](): CRM_Core_Error::exceptionHandler(Object(DB_Error))
    #2 /var/www/html/civicrm/sites/all/modules/civicrm/packages/PEAR.php(931): call_user_func((Array:2), Object(DB_Error))
    #3 /var/www/html/civicrm/sites/all/modules/civicrm/packages/DB.php(976): PEAR_Error->PEAR_Error("DB Error: no such table", -18, 16, (Array:2), "INSERT INTO civicrm_sdd_mandate (reference , source , entity_table , entity_i...")
    #4 /var/www/html/civicrm/sites/all/modules/civicrm/packages/PEAR.php(564): DB_Error->DB_Error(-18, 16, (Array:2), "INSERT INTO civicrm_sdd_mandate (reference , source , entity_table , entity_i...")
    #5 /var/www/html/civicrm/sites/all/modules/civicrm/packages/DB/common.php(1905): PEAR->raiseError(NULL, -18, NULL, NULL, "INSERT INTO civicrm_sdd_mandate (reference , source , entity_table , entity_i...", "DB_Error", TRUE)
    #6 /var/www/html/civicrm/sites/all/modules/civicrm/packages/DB/mysql.php(895): DB_common->raiseError(-18, NULL, NULL, NULL, "1146 ** Table 'escolcat_civicrm.log_civicrm_sdd_mandate' doesn't exist")
    #7 /var/www/html/civicrm/sites/all/modules/civicrm/packages/DB/mysql.php(328): DB_mysql->mysqlRaiseError()
    #8 /var/www/html/civicrm/sites/all/modules/civicrm/packages/DB/common.php(1216): DB_mysql->simpleQuery("INSERT INTO civicrm_sdd_mandate (reference , source , entity_table , entity_i...")
    #9 /var/www/html/civicrm/sites/all/modules/civicrm/packages/DB/DataObject.php(2442): DB_common->query("INSERT INTO civicrm_sdd_mandate (reference , source , entity_table , entity_i...")
    #10 /var/www/html/civicrm/sites/all/modules/civicrm/packages/DB/DataObject.php(1060): DB_DataObject->_query("INSERT INTO civicrm_sdd_mandate (reference , source , entity_table , entity_i...")
    #11 /var/www/html/civicrm/sites/all/modules/civicrm/CRM/Core/DAO.php(451): DB_DataObject->insert()
    #12 /var/www/html/civicrm/sites/default/files/civicrm/custom_ext/org.project60.sepa-master/CRM/Sepa/BAO/SEPAMandate.php(84): CRM_Core_DAO->save()
    #13 [internal function](): CRM_Sepa_BAO_SEPAMandate::add((Array:16))
    #14 /var/www/html/civicrm/sites/all/modules/civicrm/api/v3/utils.php(1282): call_user_func_array((Array:2), (Array:1))
    #15 /var/www/html/civicrm/sites/default/files/civicrm/custom_ext/org.project60.sepa-master/api/v3/SepaMandate.php(38): _civicrm_api3_basic_create("CRM_Sepa_BAO_SEPAMandate", (Array:16))
    #16 /var/www/html/civicrm/sites/all/modules/civicrm/Civi/API/Provider/MagicFunctionProvider.php(89): civicrm_api3_sepa_mandate_create((Array:16))
    #17 /var/www/html/civicrm/sites/all/modules/civicrm/Civi/API/Kernel.php(96): Civi\API\Provider\MagicFunctionProvider->invoke((Array:9))
    #18 /var/www/html/civicrm/sites/all/modules/civicrm/api/api.php(23): Civi\API\Kernel->run("SepaMandate", "create", (Array:16), NULL)
    #19 /var/www/html/civicrm/sites/default/files/civicrm/custom_ext/org.project60.sepa-master/CRM/Sepa/Page/CreateMandate.php(167): civicrm_api("SepaMandate", "create", (Array:16))
    #20 /var/www/html/civicrm/sites/default/files/civicrm/custom_ext/org.project60.sepa-master/CRM/Sepa/Page/CreateMandate.php(44): CRM_Sepa_Page_CreateMandate->createMandate("OOFF")
    #21 /var/www/html/civicrm/sites/all/modules/civicrm/CRM/Core/Invoke.php(312): CRM_Sepa_Page_CreateMandate->run((Array:3), NULL)
    #22 /var/www/html/civicrm/sites/all/modules/civicrm/CRM/Core/Invoke.php(86): CRM_Core_Invoke::runItem((Array:13))
    #23 /var/www/html/civicrm/sites/all/modules/civicrm/CRM/Core/Invoke.php(54): CRM_Core_Invoke::_invoke((Array:3))
    #24 /var/www/html/civicrm/sites/all/modules/civicrm/drupal/civicrm.module(489): CRM_Core_Invoke::invoke((Array:3))
    #25 [internal function](): civicrm_invoke("sepa", "cmandate")
    #26 /var/www/html/civicrm/includes/menu.inc(519): call_user_func_array("civicrm_invoke", (Array:2))
    #27 /var/www/html/civicrm/index.php(21): menu_execute_active_handler()
    #28 {main}

The table exists, it complains at DAO.php -> public function save()

Is there anything I am missing?

**Comment by systopia** [comment]
Hi @enboig. This is not a CiviSEPA problem. The reason you're getting this error is that you are using the logging function. You need to disable it before you install or update extensions (that modify the database), and then re-enable it after you're done. 

If you were following some kind of instructions for installing extensions, you should consider extending the instructions to mention this.

**Comment by enboig** [comment]
I have made another clean install with drupal 7, CiviCRM 4.6.8 and the "master" version of civicrm sepa and I am quit lost at using it. Could you check if the documentation at https://wiki.civicrm.org/confluence/display/CRM/CiviSEPA+Setup+Instructions is still valid? I may have misunderstood the workflow but I can't find my error.

**Comment by systopia** [comment]
First of all, please don't use the ``master`` version unless you know what you're doing, best is to stick to the releases: https://github.com/Project60/org.project60.sepa/releases (as the documentation states).

The documentation you stated not written by me, but it looks fine on a quick glance. 

Also, please ask a more precise question. "I'm lost at using it" is hard for me to answer.

**Comment by enboig** [comment]
I used master because 1.2rc doesn't appear to support civicrm 4.6 (I checked info.xml file).
You are right about my answear, sorry. I created a module for drupal some years ago and my workflow was:
1) add IBAN to contacts (just once)
2) create a mandate
3) add as many contacts as you want to the mandate (using a simple list)
4) close the mandate and send it to the bank

If I understand, in this case I have to:
1) Create a mandate user by user
2) add them to a batch (ensuring total and count is ok)
3) close the batch and generate the XML

Is this correct?

**Comment by systopia** [comment]
> 1) add IBAN to contacts (just once)
> 3) add as many contacts as you want to the mandate (using a simple list)
> 4) close the mandate and send it to the bank
> 2) add them to a batch (ensuring total and count is ok)

I'm really not sure what you're doing there. Maybe add some screen shots?
