### ISSUE TITLE
Button "SEPA Einzug erfassen" invisible in new contacts

### ISSUE THREAD

**Issue by mielert** [Project60/org.project60.sepa#322]
How ever it's called in English, the button to create a mandate is invisible in newly created contacts so you've got to reload the page.

**Comment by systopia** [comment]
@mielert: It works fine for me, could you give us more detail? I assume CiviSEPA 1.2, CiviCRM 4.6.8. Maybe a screenshot would help.

**Comment by systopia** [comment]
Closed due to inactivity
