### ISSUE TITLE
Underscores? <fileFormat>pain_008_001_02</fileFormat>

### ISSUE THREAD

**Issue by magnolia61** [Project60/org.project60.sepa#324]
Hi Bjorn,
The xml file I that I generate with the current master gets me the following line in there,
that wasn't in there a few months ago.
<fileFormat>pain_008_001_02</fileFormat>

Unfortunately our dutch bank rejects the format with the underscores.
Are the underscores desired behaviour? 
The proper format seems to be:
<fileFormat>pain.008.001.02</fileFormat>
(with dots instead of underscores)

Just wondering :-) (or do you suspect is a flaw in my installation?)

**Comment by systopia** [comment]
Are you using the unstable ``master`` branch? Then it's probably due to some changes (see https://github.com/Project60/org.project60.sepa/issues/298).

@scardinius: Could you fix this and provide a PR?

**Comment by magnolia61** [comment]
This can be closed I guess by scardinius fix

**Comment by systopia** [comment]
Great.
