### ISSUE TITLE
civicrm_sdd_creditor add column `payment_instrument_id`

### ISSUE THREAD

**Issue by magnolia61** [Project60/org.project60.sepa#325]
Hi Bjorn, In the sql/upgrade.sql there is a line:
#issue 13: creditor more complete
alter table civicrm_sdd_creditor add column `payment_instrument_id` int unsigned    COMMENT 'FK to civicrm_payment_instrument';
But this is not found in the sql/sepa.sql
Should the collumn be ther or not? Probably the two sql files need to be aligned.

**Comment by systopia** [comment]
Good point, @magnolia61, thanks. I'll investigate...

**Comment by systopia** [comment]
Hm, as far as I can tell, https://github.com/Project60/org.project60.sepa/blob/master/sql/upgrade.sql is not used in the current version CiviSEPA. Currently there's no upgrader implemented.

@tttp / @antrik: Am I correct? Can we delete this file, IMHO it's not helpful.

**Comment by antrik** [comment]
This file has never been "used" in the sense that the software did anything with it; rather, it's been there as some kind of guide for doing upgrades manually... At any rate, it's totally obsolete, and can be safely dropped.

(In the SfE variant, we started implementing automatic upgrades for any changes that happened after the first version that went into production. Don't know how you handle it in the systopia/Project60 variant; but either way, this file hasn't been updated there either, so it's totally useless.)
