### ISSUE TITLE
Mandate Packages

### ISSUE THREAD

**Issue by systopia** [Project60/org.project60.sepa#330]
Polish banks have a slightly (but significantly) different workflow, explained here https://github.com/Project60/org.project60.sepa/pull/319

@scardinius is working on implementing that, development branch is [dev_mandate_packages](https://github.com/Project60/org.project60.sepa/tree/dev_mandate_packages)

**Comment by scardinius** [comment]
to close, #319 is closed now

**Comment by systopia** [comment]
Thanks, @scardinius
