### ISSUE TITLE
Fail to generate the new RCUR if creditor mandate_active=0

### ISSUE THREAD

**Issue by tttp** [Project60/org.project60.sepa#334]
So the field is meant to be:
If true, new Mandates for this Creditor are set to active directly upon creation; otherwise, they have to be activated explicitly later on

So if they are explicitly activated, they should be generating a new batch, but
function civicrm_api3_sepa_logic_update($params) {
     $creditor_query = civicrm_api('SepaCreditor', 'get', array('version' => 3, 'option.limit' => 99999));

but in civicrm_api3_sepa_alternative_batching_update (or in the other api doing the same)
it only takes the creditro that have mandate_active=1

It's a bug,  @systopia, is this clear or do you think there is a confusion of the meaning of mandate_active?

**Comment by systopia** [comment]
I think you're right, this should be a bug. 

@tttp: Could you create a PR, so I can be sure what you mean?

**Comment by systopia** [comment]
pulled to ``master`` and ``1.2.x``
