### ISSUE TITLE
Search recurring contributions @4.6 confusing

### ISSUE THREAD

**Issue by bjendres** [Project60/org.project60.sepa#335]
With CiviCRM 4.6 they included a "Recurring Contributoins" options into the "Find Contributions" form. In the context of CiviSEPA this is confusing, since at least the "Next scheduled" doesn't work.
<img width="746" alt="screenshot" src="https://cloud.githubusercontent.com/assets/3448869/10219687/59a853b0-6841-11e5-92e2-6d698df29402.png">

We should either make it work, or make it somehow more clear to the user what to expect.

**Comment by michau** [comment]
We could work on this and get it implemented within next few weeks if we decide what needs to be done here.

@scardinius What do you think?

**Comment by systopia** [comment]
I think, that's a very good idea :)

**Comment by tttp** [comment]
Obviously, getting it working it a better option. @systopia did you look at the reason of the search not working? is this because the contributions aren't necessarily created, or that the search is based on a field (next_scheduled_date) that we don't use the same way the search expects, or...?

**Comment by systopia** [comment]
@tttp No, haven't looked into this yet.

**Comment by scardinius** [comment]
Field `next_sched_contribution_date` is not setting up by SEPA and it's looks like a reason of this issue.

@michau, Yes, I could work on this :)

**Comment by bjendres** [comment]
obsolete with #431
