### ISSUE TITLE
Usability issues with hidden BIC

### ISSUE THREAD

**Issue by systopia** [Project60/org.project60.sepa#342]
Feature #326 lets you hide the BIC if the "Little BIC Extension" is able to look it up. However in the following scenario the behaviour is confusing:
 1. Go to a donation page, select SEPA payment processor
 2. Enter IBAN
 3. Hit "Contribut" button BEFORE BIC lookup returns
 4. That will cause the form validation to complain about the missing BIC
 5. The from will be displayed with the error...
 6. ... but the BIC will be automatically filled with the looked up value, since the IBAN is present
 7. This will lead to the confusing situation, that the user is told that the BIC is wrong/missing although it's correctly filled out

**Comment by systopia** [comment]
I tried fixing this by looking a missing BIC up during validation (see https://github.com/Project60/org.project60.sepa/tree/dev_342), but at this point it's too late: the validation errors have already been raised (and cannot be unset in the validation hook).

Good ideas anyone?

**Comment by tttp** [comment]
Does the bic need to be mandatory and do we need the lookup on the client side if hidden?
ie. if hidden:
1) bic is not displayed but not mandatory
2) no lookup
3) on the pre-save hook, fetch the bic 

X+

**Comment by systopia** [comment]
Well, currently BIC *is* mandatory. That's why we can't use hooks or similar, because we need user interaction in case it fails....

**Comment by tttp** [comment]
To clarify my thought:

It can be set as non mandatory, and the verification hook does flag it in
error if empty and the local lookup doesn't work

**Comment by systopia** [comment]
Hm, that would work, but it sounds rather dirty :-) We have to keep a lot of scenarios in mind here: multiple PPs, "hide BIC" enabled/disabled, "Little BIC" installed/not installed, etc. 
That's too "shaky" to squeeze it into 1.2.1, so I'll leave it for the moment.

**Comment by systopia** [comment]
merged to ``master`` and ``1.2.x``
