### ISSUE TITLE
Contribution page asking for credit card instead of IBAN/BIC

### ISSUE THREAD

**Issue by Ash-Crow** [Project60/org.project60.sepa#343]
I updated CiviCRM to 4.4.19 and the civisepa module through git (I'm on the master branch and up-to-date). Since then, instead of the BIC/IBAN informations required for SEPA payments, the contribution page displays a non-functioning credit card selector (see screenshot or https://dons.wikimedia.fr/civicrm/contribute/transact?reset=1&id=74 )

![capture du 2015-11-02 11 08 56](https://cloud.githubusercontent.com/assets/765956/10886959/d1ddd510-8184-11e5-94bb-fe377295a155.png)

Screenshots of the config pages:

![capture du 2015-11-02 17 17 11](https://cloud.githubusercontent.com/assets/765956/10887089/969397f0-8185-11e5-989c-8375efd7f34c.png)
![capture du 2015-11-02 17 15 29](https://cloud.githubusercontent.com/assets/765956/10887090/96a57a10-8185-11e5-9a68-7a5a2374e0b1.png)
![capture du 2015-11-02 17 14 34](https://cloud.githubusercontent.com/assets/765956/10887092/96c2c8e0-8185-11e5-9bf1-d86bd2662ac4.png)
![capture du 2015-11-02 17 13 17](https://cloud.githubusercontent.com/assets/765956/10887091/96b6a808-8185-11e5-8900-367a38d5e90a.png)

**Comment by tttp** [comment]
It displays the default "dummy" card it seems, ie the specific layout from sepa isn't displayed. I'm looking into that...

**Comment by systopia** [comment]
Thanks @Ash-Crow, excellent documentation :) Could you add the CiviSEPA Version?

@tttp: Any progress?

**Comment by Ash-Crow** [comment]
Not too sure what version you need.

git describe
1.2-45-g7a01a94

**Comment by systopia** [comment]
@Ash-Crow: That means you're using the bleeding edge ``master`` version, which is also not compatible with CiviCRM 4.4 any more. You would want to use one of the [official releases](https://github.com/Project60/org.project60.sepa/releases), ideally the 1.2 version, or the 1.2.1 release candidate that I will create very soon.

**Comment by tttp** [comment]
Its on the 1.2.x branch
    git branch:
      * 1.2.x
      master

Weird, everything seems to be rightly given to the core (eg the right
template) just happily ignoed ;(

@Ash-Crow, I'm downgrading to the release point at  1.2 see if it's there
(I doubt so).

@systopia, we discussed changing the payment type (1 vs 2...) but looking
at the db level, it isn't that

X+

**Comment by tttp** [comment]
Found the issue, the payment type wasn't updated on the existing payment processor, and had an historical value instead of the correct one.
