### ISSUE TITLE
Mandate creation fails if the contribution page is too long

### ISSUE THREAD

**Issue by tttp** [Project60/org.project60.sepa#344]
The error message being:

8000: Couldn't create SEPA mandate. Error was: Value for source is 82 characters - This field has a maxlength of 64 characters.

Easy fix: trunk the source so it's max 64 char. That will teach the @Ash-crow to have a language that is sooo long ;)

**Comment by systopia** [comment]
@tttp: Cool. Could you create a PR? I'll merge into master and 1.2.2 (after 1.2.1 is released)

**Comment by tttp** [comment]
yeap

**Comment by systopia** [comment]
@tttp: I just committed your fix to ``master`` and ``1.2.x``
