### ISSUE TITLE
Error 8000: Couldn't create SEPA mandate

### ISSUE THREAD

**Issue by Ash-Crow** [Project60/org.project60.sepa#346]
Since the resolution of bug #343 the good fields appears again but people still cannot register a new donation : on validation they receive an error message : "8000: Couldn't create SEPA mandate. Error was: Value for source is 84 characters - This field has a maxlength of 64 characters." 

(The donation page is https://dons.wikimedia.fr/civicrm/contribute/transact?reset=1&id=74 )

**Comment by tttp** [comment]
duplicated of #344
