### ISSUE TITLE
Cannot edit SEPA contributions

### ISSUE THREAD

**Issue by Ash-Crow** [Project60/org.project60.sepa#347]
When we try to edit a contribution whose payment has been refused (to put their status to cancel), we get a error message : "This contribution has a mandate, its payment instrument has to be 'RCUR'" (on a popup on the top-right of the page, and on the line with the select "Payé par" (which has the SEPA DD, which is the correct one I think.)

**Comment by tttp** [comment]
Missing migration of that data I think, checking monday...
