### ISSUE TITLE
Labels wrong with CiviCRM 4.6.10+

### ISSUE THREAD

**Issue by systopia** [Project60/org.project60.sepa#350]
CiviSEPA uses the existing bank account number and the bank id field to record the IBAN and BIC. For this purpose the labels are adjusted. 

Unfortunately, after some changes to the core of CiviCRM 4.6.10+, the labels of the IBAN/BIC fields are not changed any more, which leads to a confusing input form.

See also https://github.com/Project60/org.project60.sepa/issues/348

**Comment by systopia** [comment]
If you're currently having trouble with this, you might want to have a look at https://github.com/systopia/org.project60.sepa/tree/dev_4.6.10, which also contains an untested(!) fix for #333. Test well before using this, though!

**Comment by magnolia61** [comment]
I will try to test the dev_4.6.10 code on some of my installs and report back. Is Nikobo's workaround (https://github.com/Project60/org.project60.sepa/commit/5ac3ca5ab3e5f9ef8a157e030ed64864e33fd33f) included in your 4.6.10 branch?

**Comment by nikobo** [comment]
@magnolia61 Yes, the branch dev_4.6.10 does contain this workaround

**Comment by intombi** [comment]
Hi , unfortunately branch dev_4.6.10 does not fix the issue for us. There is still the Label "Kontonummer" und "Bankleitzahl" instead of "IBAN" and "BIC". 
Is there anything else I can check/do ?

**Comment by systopia** [comment]
It's possible that Niko's hotfix doesn't work on you environment (Joomla?). Have you tried executing the JS commands in the console? If it works you can just dump them as a JS script in the HTML page header or footer of your donation page...

**Comment by intombi** [comment]
Executing the JS commands in the console worked! Thanks

**Comment by systopia** [comment]
Should be fixed with 1.2.2

@intombi: Could you verify this?

**Comment by systopia** [comment]
no feedback -> closed
