### ISSUE TITLE
Compatibility with civicrm 4.7

### ISSUE THREAD

**Issue by magnolia61** [Project60/org.project60.sepa#351]
Hi Bjorn, I'm posting this issue as a placeholder for civicrm 4.7 compatibility. From what is within my possibilities I want to pro-actively try to help get civisepa to work with 4.7 (which is almost stable, now at beta3). In this issue we can try to collect the opportunities  and pitfalls for civisepa with civicrm 4.7

**Comment by magnolia61** [comment]
When opening the admin settings (civicrm/admin/setting/sepa?reset=1) I get the following fatal error in 4.7:
Fatal error: Call to undefined method CRM_Core_Config::countryLimit() in /home/ozklab/domains/onvergetelijk.nl/public_html/porto/sites/all/modules/civicrm_extensions/org.project60.sepa/CRM/Admin/Form/Setting/SepaSettings.php on line 101

**Comment by nikobo** [comment]
#352 is part of this, at least for beta 2

**Comment by systopia** [comment]
Hi @magnolia61. Thanks for your initiative. We haven't started looking into this, but afaik they fundamentally changed the payment processor structures (again), so I expect some problems there.

**Comment by magnolia61** [comment]
Some observations running in civicrm 4.7:
- When I try to go to the civisepa setting I get:
   Fatal error: Call to undefined method CRM_Core_Config::countryLimit() 
- Updating a batch in the civisepa dashboard seems to go ok, but updating it a 2nd time gets:
  Notice: Undefined index: id in civicrm_extensions/org.project60.sepa/CRM/Sepa/Logic/Batching.php on line 433

**Comment by magnolia61** [comment]
I know 4.7 compatibility is still not available/funded, so purely FYI and to document for future use:
When (in civicrm 4.7.7) I try to look at the contributions of an active group I get
Cannot read SEPA transaction group [350]. Error was: 'A fatal error was triggered: is not of type String'
The url is: https://www.onvergetelijk.nl/civicrm/sepa/listgroup?group_id=350

**Comment by systopia** [comment]
@magnolia61: Yes, we still don't have anyone willing to fund this. But thanks for documenting...
