### ISSUE TITLE
duplicate of angular?

### ISSUE THREAD

**Issue by tttp** [Project60/org.project60.sepa#354]
Hi @scardinius 

For the list of mandates, you have added angular, is this not working to use the core angular from civi?

https://github.com/Project60/org.project60.sepa/tree/master/js

**Comment by nikobo** [comment]
I think the problem here is that we try to keep the module compatible with CiviCRM  version 4.4, but AngularJS was introduced with 4.5, afaik.

**Comment by tttp** [comment]
@nikobo good point, but we should only include angular if version <= 4.4.

If I do the code change, do you have a 4.4 to test if it still work on 4.4? I don't, so wouldn't feel too conformable pushing something not tested ;) 

http://civicrm.stackexchange.com/questions/8796/whats-the-best-way-to-code-for-extensions-to-work-for-multiple-civicrm-versions

**Comment by systopia** [comment]
Well, my plan was to release @scardinius' changes with CiviSEPA 1.3, which would then only be compatible with CiviCRM 4.6+. What do you think?

**Comment by tttp** [comment]
on my side, no one is left on 4.4, so fine

Might be cleaner to make a branch 4.4-obsoleted just before the merge, so
if there is someone left on 4.4, it might be easier for them to take over
the maintenance of that branch if so they choose.

**Comment by systopia** [comment]
Hm, yes. Technically, that would be the ``1.2.x`` branch that's already there. The ``master`` already has the 4.4 version removed from the compatibility list in the info.xml

**Comment by systopia** [comment]
@tttp Can I close this, or do you want to mark the ``1.2.x`` branch explicitly as "last 4.4" or something?
