### ISSUE TITLE
Mandate reports

### ISSUE THREAD

**Issue by systopia** [Project60/org.project60.sepa#358]
We want three reports:
 * Generic (on mandate metadata)
 * OOFF (only focusing in the contribution's attributes)
 * RCUR (adding a lot of aggregated values like "contribution count", "total amount transferred", "cancelled contribution count", "cancel reason")

**Comment by tttp** [comment]
Oh my, I'm working on something along that line...  On civisualize

**Comment by systopia** [comment]
Well, both approaches will have their applications, I'm sure...

**Comment by systopia** [comment]
Is currently in test in version 1.2.3

**Comment by systopia** [comment]
merged to ``master``
