### ISSUE TITLE
contact_id not set in partial mandate

### ISSUE THREAD

**Issue by systopia** [Project60/org.project60.sepa#359]
Under certain circumstances (not fully understood), the ``$this->getVar('_contactID');`` in  [this line](https://github.com/Project60/org.project60.sepa/blob/1.2.1/CRM/Core/Payment/SDD.php#L157) doesn't yield the contact id, which can cause troubles in the further processing in the partial mandates.

Observed with CiviSEPA 1.2.1 on CiviCRM 4.4.20 on a donation page for OOFF contributions.

**Comment by tttp** [comment]
@systopia want me to see if it happens on other installations? Any quick way to identified "contactless" mandates?

**Comment by systopia** [comment]
> want me to see if it happens on other installations?

Yes, please :)

> Any quick way to identified "contactless" mandates?

Unfortunately not, mandates w/o contacts will get fixed here: https://github.com/Project60/org.project60.sepa/blob/1.2.1/CRM/Core/Payment/SDD.php#L252

But the ``create_mandate`` mandate hook will be called w/o contact_id and potentially break things.

**Comment by systopia** [comment]
merged to ``1.2.x``. Won't merge to ``master``, is most likely problem with CiviCRM 4.4.x
