### ISSUE TITLE
e mandate

### ISSUE THREAD

**Issue by tttp** [Project60/org.project60.sepa#36]
We got a "clarification letter regarding electronic mandates under the SDD Core Scheme and SDD B2B Scheme"

http://www.europeanpaymentscouncil.eu/content.cfm?page=news&news_id=508

I don't think clarification has the same meaning for them than for me. 
For what I understand: bla bla bla, each bank decides what is or isn't a valid e-mandate/e-signature bla bla may god be with you and good luck to ya all.

Can someone translate into "english for humans"? is this something we can take into account?

**Comment by systopia** [comment]
@tttp Please re-open if this is still relevant
