### ISSUE TITLE
Extension cannot be disabled when payment processor is active

### ISSUE THREAD

**Issue by bjendres** [Project60/org.project60.sepa#373]
If you have an active SEPA payment processor, you cannot disable the extension without causing severe problems with the system.

This is more a problem with CiviCRM itself than with CiviSEPA extension: The payment processor contains the implementing class name, and that class is not available any more once the extension has been disabled. But instead of treating this like an "unknown implementation" and carry, it crashes.

We hope that with the improved payment processor infrastructure coming with 4.7 that this problem will give us the tools to address this.

**Comment by tttp** [comment]
In theory when disabling, you could replace the sepa class by  the one for the dummy payment processor (and put it back when enabling it).

but bit of a hack indeed...

**Comment by systopia** [comment]
That's what I had in mind, too. But I haven't tested it yet...you?

**Comment by tttp** [comment]
Why would I disable such an awesome extension? Quitters deserve a world of
pain, it's a feature, not a bug ;)

**Comment by michau** [comment]
@tttp True dat! ;-)

**Comment by systopia** [comment]
I'll create an easy fix by setting ``civicrm_payment_processor.class_name`` to "Payment_Dummy" when disabling. When enabling we can restore the value, because the connection via ``payment_processor_type_id`` is still there....

**Comment by systopia** [comment]
merged to ``master``, but will also releasde with ``1.2.3``...

**Comment by bjendres** [comment]
Fixed with ``1.5`` because payment processors were migrated to https://github.com/Project60/org.project60.sepapp
