### ISSUE TITLE
Contact page is blocked for scrolling after creating mandate

### ISSUE THREAD

**Issue by scardinius** [Project60/org.project60.sepa#380]
Hi,

I found weird and interesting bug. After creating mandate, contact page is blocked for scrolling.
1. On Chrome _48.0.2564.116_ - I can't scroll by arrows, page up/down keys and mouse
2. On Firefox _44.0.2_ - I can't scroll only by mouse (arrows and page up/down keys works fine)

This bug occurs after click on both links `Record SEPA Contribution`:
- below `Action` button,
- on `Contributions` tab.

**Comment by systopia** [comment]
@scardinius Can you still reproduce it with the (upcoming) ``1.4``?

**Comment by systopia** [comment]
Couldn't reproduce with upcoming ``1.4``, @scardinius please re-open if you can.
