### ISSUE TITLE
closing a OOFF group might end up closing unrelated mandates

### ISSUE THREAD

**Issue by tttp** [Project60/org.project60.sepa#383]
So interesting bug: we had a RCUR contribution that was never debited, and it seems that the mandate for RCUR was closed when we closed an (unrelated) OOFF contribution that had the same ID than the recurring contribution

@scardinius analysis
https://github.com/Project60/org.project60.sepa/blob/master/CRM/Sepa/Logic/Group.php#L56
we close all mandates, not only OOFF mandates

**Comment by scardinius** [comment]
My proposal in order to resolve problem is here #386
