### ISSUE TITLE
XML <EndToEndId> should be contribution ID

### ISSUE THREAD

**Issue by systopia** [Project60/org.project60.sepa#385]
In the PAIN file, there is an element called &lt;EndToEndId&gt;. I thought this was an ID we could choose freely to identify the actual contribution, so naturally I assumed it was the contribution ID. This seemed to be supported by the the code (see  [here](https://github.com/Project60/org.project60.sepa/blob/1.2.2.beta1/templates/CRM/Sepa/xml/TransactionGroup.tpl#L55) and [here](https://github.com/Project60/org.project60.sepa/blob/1.2.2.beta1/CRM/Sepa/BAO/SEPATransactionGroup.php#L70:L130).)

However it turns out that `{$contribution.id}` is actually the mandate ID.

@tttp: I think you wrote that code in the first place... Is that by design or is this a bug? Is there any reason not to use the contribution ID?

**Comment by tttp** [comment]
Hi,

the mandate id is in <MndtId>. The end to end is supposed to be unique, but don't recall if it's unique per file or across all files.

Is there an issue to keep the contribution id?

**Comment by systopia** [comment]
> Is there an issue to keep the contribution id?

That's my point, &lt;EndToEndId&gt; is currently NOT the contribution ID, but the mandate ID. I'm asking whether you can see a problem in changing it to be the contribution ID...

**Comment by tttp** [comment]
Sorry, I misread you. yes, contribution id is better then

**Comment by systopia** [comment]
Ok, will change that in ``1.3`` then.

**Comment by systopia** [comment]
Revisiting this, I think it's a bug after all. The problem is the the ``id`` field in a ``CRM_Core_DAO`` seems to be rather volatile - even if the ``id``  column in the SQL query itself contains the contribution ID, the ``id`` field in the result has the mandate ID.

I say this needs fixing, since the mandate ID is by no means unique.

See code at: https://github.com/Project60/org.project60.sepa/blob/1.2.3/CRM/Sepa/BAO/SEPATransactionGroup.php#L70-L98
