### ISSUE TITLE
Duplicate collection if receive time changed

### ISSUE THREAD

**Issue by systopia** [Project60/org.project60.sepa#390]
During the batching process, CiviSEPA looks for existing contributions with a ``receive_date`` equal to the collection date. However, if the time part of the the ``receive_date`` has been modified (i.e. by CiviBanking) before the actual collection date, the algorithm won't find it, and subsequently creates a new collection.

This usually shouldn't happen, since CiviBanking should only process the related transactions only AFTER the collection date, but sometimes banks are a little weird.

This highlights once more, that we need another connection between mandate/contribution/installment, since the date is unreliable.

**Comment by tttp** [comment]
Very very good point. Want to brainstorm or you have a plan? contrib recur has a last contrib id, we could use that as the reference?

**Comment by systopia** [comment]
Well, I was thinking about using the contribution's ``trxn_id``, e.g. setting it to "[mandate_reference]-[collection-date]". This way, people could (later) move the contribution around, but it'll always be identifiable as this particular installment. Would be helpful when searching for contributions as well...

**Comment by systopia** [comment]
Is currently in test in version 1.2.3

**Comment by systopia** [comment]
merged to ``master``
