### ISSUE TITLE
LittleBIC error message

### ISSUE THREAD

**Issue by Fabian-SYSTOPIA** [Project60/org.project60.sepa#394]
CiviSEPA Version: 1.2.2; CiviCRM Version 4.16.14; Not littleBIC installed

When I select "Create SEPA-Mandate" from a contact's contribution View an error pops up: "API (Bic, findbyiban) does not exist (join the API team and implement it!)."

Maybe the check if LittleBIC is installed is not working?!

**Comment by systopia** [comment]
Is currently in test in version 1.2.3

**Comment by systopia** [comment]
merged to ``master``

**Comment by systopia** [comment]
Unfortunately, this is still present. Problem is, that the ``Extension.get`` call apparently doesn't give a &^$% about the ``key`` parameter.

**Comment by tttp** [comment]
@systopia easier to track the is_error and handle it differently than just display a "no extension" error?

**Comment by systopia** [comment]
> @systopia easier to track the is_error and handle it differently than just display a "no extension" error?

Not even. The idea was that if little BIC is not installed there is simply no lookup - but no warning or notification. It seems to work quite well now.
