### ISSUE TITLE
BUG: Cannot load group #x - "is not of type String"

### ISSUE THREAD

**Issue by systopia** [Project60/org.project60.sepa#395]
In the recent CiviCRM 4.6 versions (observed on 4.6.17) the following error appears when dealing with SDD groups, like closing, or accessing them via API:
```
Cannot load group #xx.

Error was: A fatal error was triggered: is not of type String
```

**Comment by systopia** [comment]
Is currently in test in version 1.2.3

**Comment by magnolia61** [comment]
fyi: this also fixed this issue in civicrm 4.7

**Comment by systopia** [comment]
I'll merge it into 1.3 soon, which will (eventually) be 4.7 compatible

**Comment by systopia** [comment]
merged to ``master``
