### ISSUE TITLE
cancel_reason | end_reason => error message

### ISSUE THREAD

**Issue by mielert** [Project60/org.project60.sepa#401]
I get an error message when saving a mandate with filled out cancel_reason or end_reason.
4.7, 1.2.3.beta

**Comment by systopia** [comment]
Thanks @mielert. 

I'm not quite sure what you mean but I could create a mandate with an end date on 4.6 with the latest Beta - so this would be https://github.com/Project60/org.project60.sepa/issues/351.

Could you specify what process/form you're referring to? Ideally with a screen shot?

**Comment by mielert** [comment]
@systopia I think this is a problem of 4.7
If I'm going to cancel a mandate, I've got to give a reason. This reason throws an error message.

Filling in "testgrund"
<img width="854" alt="bildschirmfoto 2016-08-04 um 14 44 20" src="https://cloud.githubusercontent.com/assets/937362/17402173/0f6c50cc-5a52-11e6-81a4-58e2dfa8c89f.png">
Saving (Clicking "Abbrechen")
Error Message:
<img width="385" alt="bildschirmfoto 2016-08-04 um 14 44 29" src="https://cloud.githubusercontent.com/assets/937362/17402172/0f6b8eda-5a52-11e6-89e8-a7cce1a65e96.png">

Sorry, just wanted to file the bug. Don't have time to look for it before September.

**Comment by systopia** [comment]
> Sorry, just wanted to file the bug. Don't have time to look for it before September.

No worries, thank you for reporting!

**Comment by Fabian-SYSTOPIA** [comment]
I was able to reproduce this on a testing environment

**Comment by systopia** [comment]
The reason for this behaviour is [CRM-14901](https://issues.civicrm.org/jira/browse/CRM-14901). We use a note attached to the mandate to store the cancel reason, but this change prevents us from doing it in CiviCRM 4.7. I will try to find a workaround, but a proper fix (see #409) is a lot of work...

**Comment by Fabian-SYSTOPIA** [comment]
Tested with 1.2.4 alpha - is working now
