### ISSUE TITLE
Upgrade from sfe-ev/ssepa/show_recur branch to Project60/1.2.3

### ISSUE THREAD

**Issue by czerwinski1977** [Project60/org.project60.sepa#403]
Drupal 7.50; CiviCRM 4.4.21
I am using the [sfe-ev/ssepa/show_recur](https://github.com/sfe-ev/ssepa/tree/show_recur) branch and it kind of works for me. Now I want to upgrade to latest Project60 release (1.2.3) but I am having issues: Most prominently, I cannot dig into SEPA groups, I always end up at the overview page. I have also tried CiviCRM 4.5 and 4.6 without success.

Q: Is there a reasonable upgrade path from the branch I am using to 1.2.3?
Q: CiviSEPA supports 4.4, 4.5, and 4.6 -- equally, or is there a recommendation for a specific version?

Thanks! Reinhard

**Comment by systopia** [comment]
Hi @czerwinski1977.

>  I have also tried CiviCRM 4.5 and 4.6 without success.

That makes me think that this is a problem with the data created by the ``sfe-ev`` branch.

> Q: Is there a reasonable upgrade path from the branch I am using to 1.2.3?

I'm not sure. @Detsieber oder @antrik would be the best contacts to ask this. I personally have not been involved in the ``sfe-ev`` branch.

> Q: CiviSEPA supports 4.4, 4.5, and 4.6 -- equally, or is there a recommendation for a specific version?

It should, however since few people a re still on 4.4, maybe some 4.4 specific bugs slipped through . But if in your case you observed the same problem on 4.6, I doubt this applies to you.

**Comment by antrik** [comment]
Woah, I wasn't aware anyone was actually using this ancient code in production...

@systopia IIRC this branch is only a small change compared to what ended up the branching point between the SfE and the systopia variants, i.e. this question applies for upgrade attempts to either version.

@czerwinski1977 I don't think there is any official upgrade path from this ancient code. Probably the only thing you can do is transitioning your existing data to the new database scheme by issuing appropriate SQL statements. You might need external consulting for that, which might end up pretty expensive. Sorry for that -- but then again, this was never an officially released/supported version...

**Comment by czerwinski1977** [comment]
Thank you for your replies, I will try to mod the tables.

Cheers, Reinhard

**Comment by systopia** [comment]
@Detsieber Can we close this?

**Comment by Detsieber** [comment]
The Ssepa Extension is deprecated and won't receive further updates. Especially, it is not ready for CiviCRM 4.7. I recommend migrating to CiviSEPA!

However, that migration is not trivial - if anybody out there needs support in changing to CiviSEPA / Project60, please contact me: I have outlined a migration plan, containing the manual worksteps and some sql statements for converting some of the data.
