### ISSUE TITLE
start_date no more editable

### ISSUE THREAD

**Issue by mielert** [Project60/org.project60.sepa#406]
When editing a mandate no matter what start date I select, the old one is used. So I have to create a new mandate from scratch.

Release Date: 2016-08-18
System: php 5.6.27, Drupal 7.51, Civi 4.7.12

**Comment by systopia** [comment]
Sorry, I can't reproduce this.

@mielert: Please re-open with screen shot / instructions how to reproduce.

**Comment by mielert** [comment]
Sorry, I don't have access to a CiviCRM-instance any more.
