### ISSUE TITLE
Issue a warning when leaving the "close group" screen

### ISSUE THREAD

**Issue by systopia** [Project60/org.project60.sepa#407]
Somebody cleverly suggested to mark the "close SEPA group" screen as 'edited' so you would get a warning when leaving that screen without consciously closing the group or leaving it open.

This won't fix the problem with left-open groups in general, but it could make it less likely to forget.

**Comment by Fabian-SYSTOPIA** [comment]
Tested with 4.6.21 and working fine - will test with 4.7 soon

**Comment by Fabian-SYSTOPIA** [comment]
Tested 1.2.4 beta and working as expected (warning is shown)
