### ISSUE TITLE
PHP7 compatibility: Error: Call to undefined function split() 

### ISSUE THREAD

**Issue by magnolia61** [Project60/org.project60.sepa#411]
Thanks for the 1.2.4 beta1 release. Just tried it on drupal 7.5.2 civicrm 4.7.13 and PHP7
Using the civisepa admin settings I get the following error when saving the default values:

Error: Call to undefined function split() in CRM_Sepa_Logic_Settings::getListSetting() (line 86 of /home/xyz/domains/ourdomain.nl/public_html/sites/all/modules/civicrm_extensions/org.project60.sepa/CRM/Sepa/Logic/Settings.php).

Somewhere I found that for PHP7 the split function is deprecated and explode can be used instead.
Just reporting FYI ;-)

**Comment by tttp** [comment]
Hi,

Thanks for the report. Is the rest of civi working in PHP7? 
the latest update I have was that it relies on several key libraries (eg pear ones) that aren't compatible with PHP7

**Comment by magnolia61** [comment]
Working flawlessly in production for a month now, using even registrations and contributions. And: all much faster!

**Comment by systopia** [comment]
@magnolia61: Thanks for the report. Care to share you patch?

**Comment by magnolia61** [comment]
I have no patch, just reporting.

**Comment by DanielvV** [comment]
Works for me

**Comment by systopia** [comment]
Released with 1.2.5.beta1
