### ISSUE TITLE
Token value blocks mass mailing

### ISSUE THREAD

**Issue by dragonjon** [Project60/org.project60.sepa#425]
I have updated to V.1.2.4 but I have problems sending the newsletter.
With the previous version 1.2.3 had the same problem sporadically, at the moment it is not possible to send newsletter.
My version of Civicrm is 4.5.8
Drupal 7.53
When I send a newsletter, it is not sent.
I review Send Scheduled Mailings job log and give error
Finished execution of Send Scheduled Mailings with result: Failed, Error message: Expected one
If I run it manually not by the Cron, in the drupal log I create 100 records approximately equal with the following PHP warning
Executing using cron does not record errors

Notice: Undefined index: source in sepa_civicrm_tokenValues ​​() (line 653 of /public_html/sites/default/files/civicrm/custom/org.project60.sepa/sepa.php).
This line (653) of the file sepa.php is the following:
$values[$result->contact_id]["$prefix.source"]    = $mandate['source'];
With version 1.2.3 the error used to give in line 670 with the same code.

Thanks in advance for the work you do with this extension and all proyect60 extensions.

**Comment by dragonjon** [comment]
I do not know how but the blocking in the newsletter has been solved

Now two PHP error messages come out every time a contribution form is used and confirm page is display

Notice: Undefined index: payment_processor in sepa_pp_buildForm () (line 87 of /public_html/sites/default/files/civicrm/custom/org.project60.sepa/sepa_pp_sdd.php).

Notice: Undefined index: class_name in sepa_pp_buildForm () (line 88 of /public_html/sites/default/files/civicrm/custom/org.project60.sepa/sepa_pp_sdd.php).

**Comment by systopia** [comment]
Hi @dragonjon. Thank you for your report. 

You'll find that CiviCRM 4.5 is not supported any more as of CiviSEPA version 1.2.4. I would especially expect compatibility issues with the payment processor, which is exactly the part of the code where you get the PHP notices. That being said, notices often don't cause harm and there's a good chance it would still work. You can simply configure drupal to not show notices and warnings.

**Comment by dragonjon** [comment]
Hi @systopia thanks for the prompt response.
One last question, of the Project 60 what CiviCRM version is the best or more stable for use this extensions, we use the following extensions:
Org.project60.banking
Org.project60.sepa
Org.project60.membership
Org.project60.bic
Thanks

**Comment by systopia** [comment]
They should all be compatible with CiviCRM 4.6 at the moment, that's probably your best choice. (But of course that also depends on a lot of other factors as well).

Some of the extensions haven't been officially flagged 4.7 compatible, and some have already dropped support for 4.5 and below. You find the supported versions in the info.xml files.
