### ISSUE TITLE
Insufficient error handling when replacing mandate (Quickform)

### ISSUE THREAD

**Issue by Fabian-SYSTOPIA** [Project60/org.project60.sepa#440]
Tested with CiviCRM 4.7.22, CiviSEPA 1.2.4

How to reproduce:
- click on replace for an existing mandate
- in the form, enter a wrong IBAN and click save
- the form will be refreshed an thus loose the information on the mandate that is supposed to be replaced (changed) by the new information
- after entering the new mandate information and saving, the new mandate is created but the old is not cancelled (which would be the intended behaviour)

**Comment by systopia** [comment]
Should be fixed with #441 in ``1.4``
