### ISSUE TITLE
SEPA Group cannot be deleted in CiviCRM 4.7

### ISSUE THREAD

**Issue by appelhannes** [Project60/org.project60.sepa#442]
I have created a test mandate which I now wanted to delete. The corresponding contribution has already been deleted. When pressing the "delete" button on the CiviSEPA Dashboard, I am receiving a white screen in the browser and the group is not deleted. 

Is this a known issue and how can I fix it?
Thanks for the help.

**Comment by systopia** [comment]
I am not aware of this issue, but I need more information on the issue to help you. Which versions are you using (CiviCRM and CiviSEPA), what kind of mandate where you creating, how did you deleted the contribution....?

**Comment by appelhannes** [comment]
Thanks for your help! I am using CiviCRM version 4.7.19 and CiviSEPA version 1.2.4.

Our contribution page is not yet online and I have created the mandate using the "public" contribution page. For the preparation of the productive system, I have now deleted all test contributions I have created. I deleted the corresponding contribution to the mandate by pression the "contribution" button on the CiviSEPA dashboard.

**Comment by systopia** [comment]
I'm assuming you're talking about recurring mandate, correct? And I'm assuming you mean the "delete" button when you say "contribution" button on the dashboard, right?

Could you have a look at the PHP error log and the CiviCRM log to see if there is any message in there?

**Comment by appelhannes** [comment]
It is an OOFF mandate. There is an error message in the PHP error log file which says:

> [...]PHP Fatal error:  Call to undefined method
CRM_Core_OptionGroup::optionLabel() in
/var/www/wordpress/wp-content/uploads/civicrm/ext/org.project60.sepa/CRM/Sepa/Page/DeleteGroup.php
on line 38, referer:
http://[...]/wp-admin/admin.php?page=CiviCRM&q=civicrm%2Fsepa
[...] PHP Fatal error:  Call to undefined method
CRM_Core_OptionGroup::optionLabel() in
/var/www/wordpress/wp-content/uploads/civicrm/ext/org.project60.sepa/CRM/Sepa/Page/DeleteGroup.php
on line 38, referer:
http://[...]/wp-admin/admin.php?page=CiviCRM&q=civicrm%2Fsepa
[...] org.project60.sepa: Template 'sepa_mandate' seems to be
correctly installed. Not updated., referer:
http://[...]/wp-admin/admin.php?page=CiviCRM&q=civicrm%2Fadmin%2Fextensions&action=enable&id=org.project60.sepa&key=org.project60.sepa
[...] org.project60.sepa: Template 'sepa_mandate_pdf' seems
to be correctly installed. Not updated., referer:
http://[...]/wp-admin/admin.php?page=CiviCRM&q=civicrm%2Fadmin%2Fextensions&action=enable&id=org.project60.sepa&key=org.project60.sepa
[...] PHP Fatal error:  Call to undefined method
CRM_Core_OptionGroup::optionLabel() in
/var/www/wordpress/wp-content/uploads/civicrm/ext/org.project60.sepa/CRM/Sepa/Page/DeleteGroup.php
on line 38, referer:
http://[...]/wp-admin/admin.php?page=CiviCRM&q=civicrm%2Fsepa
<

**Comment by systopia** [comment]
Great, that helps.

It seems like ``CRM_Core_OptionGroup::optionLabel()`` was removed in CiviCRM 4.7, and nobody has noticed so far...

I'll probably put a fix in the upcoming 1.2.5, but I probably won't have the time this week.

If you don't want to wait you can simply delete the line (https://github.com/Project60/org.project60.sepa/blob/1.2.5.alpha1/CRM/Sepa/Page/DeleteGroup.php#L38) or comment it out. With a little bit of luck there won't be any side effects except the status label missing in the page.

**Comment by appelhannes** [comment]
Hello Systopia,
The line has been commented out and the mandate could be deleted.
many thanks for the help.

**Comment by systopia** [comment]
@appelhannes Could you please verify that it works in 1.2.5.alpha2?

**Comment by systopia** [comment]
Released with 1.2.5.beta1
