### ISSUE TITLE
API doesn't work correctly - ContributionRecur

### ISSUE THREAD

**Issue by DanielvV** [Project60/org.project60.sepa#444]
How to reproduce:
- Goto <yourinstallation>/civicrm/api
- Select entity ContributionRecur

**Comment by DanielvV** [comment]
It does work correctly when you have set php value short_open_tag=On

**Comment by DanielvV** [comment]
[<? is discouraged](http://php.net/manual/en/language.basic-syntax.phptags.php)

**Comment by tttp** [comment]
Hi @DanielvV, this is a mistake indeed. Could you fix and do a PR?
