### ISSUE TITLE
Full support for current SEPA rulebook as of September 2016

### ISSUE THREAD

**Issue by Detsieber** [Project60/org.project60.sepa#447]
Every year in November, a new version of the SEPA rulebook is released. The changes from November 2016 included a new PAIN file definition - this is already incorporated in CiviSEPA = pain.008-001.02 (CDD EBICS-3.0) - Thank!!

However, the following changes are still open: 
- Status FRST is obsolete (we can use RCUR from the beginning)
- Default for notice days is D+1 (instead of D+6 previously) for all payment types. (some banks require one additional day)
- IBAN-only: BIC of the debitor is not required anymore (if payment is within Euro-zone)

**Comment by tttp** [comment]
Whaaat!

I missed these points completely. It seems that I do not read enough
banking newspaper ;)

Do you have more information about it? usually, the problem isn't so much
to implement it but to get the banks play nicely with it, having some extra
information does help, usually.

Thanks to raise the issue

X+

**Comment by systopia** [comment]
@Detsieber:

> Status FRST is obsolete (we can use RCUR from the beginning)

Since it is still allowed to use FRST, I wouldn't change the system. Or can you think of a good reason?

> Default for notice days is D+1 (instead of D+6 previously) for all payment types. (some banks require one additional day)

Could you explain why configuring the notice days to 1 isn't enough?

> IBAN-only: BIC of the debitor is not required anymore (if payment is within Euro-zone)

That would be https://github.com/Project60/org.project60.sepa/issues/95, crrect?

**Comment by tttp** [comment]
I would vote to continue keeping FRST too, as it's a group that has higher changes to have problems and rejections, we tend to watch it more carefully

We use it as well for analytics, ie "real" RCUR are more likely than "FRST" that might bounce
