### ISSUE TITLE
PHP 7 compatiblity

### ISSUE THREAD

**Issue by elishowk** [Project60/org.project60.sepa#448]
Since CiviCRM is fully compatible, it may be nice to have this extension compatible too.

For example, some function are deprecated : 

```Uncaught Error: Call to undefined function split() at line 86 of org.project60.sepa/CRM/Sepa/Logic/Settings.php```

**Comment by DanielvV** [comment]
Is fixed in beta: https://github.com/Project60/org.project60.sepa/releases/tag/1.2.5.beta1

> News/bugfixes in version 1.2.5:
> ...
>     PHP7 compatibility (#411)

**Comment by tttp** [comment]
We are using it on php7, what branch are you on?

**Comment by elishowk** [comment]
Thanks, I'll close and upgrade then !
