### ISSUE TITLE
Cycle day limitations not considered when using SEPA payment processor

### ISSUE THREAD

**Issue by Fabian-SYSTOPIA** [Project60/org.project60.sepa#449]
CiviSEPA settings allow to define certain cycle day for recurring contributions. Those are properly considered when creating a SEPA mandate via the UI but not when using a CiviSEPA payment processor on a contribution page. Tested with CiviCRM 4.7.23; CiviSEPA 1.2.5.beta1 and 1.24.

To Reproduce:

1. create a creditor allow only "5" as cycle day
2. create a CiviSEPA payment processor and select that creditor
3. create a contribution page using this payment processor
4. make a recurring SEPA-contribution using that page

The Mandate will have "1" as a cycle day instead of "5"

**Comment by tttp** [comment]
Ah!

Well spotted, we had a bunch on the 1st I didn't understand how they came in.

**Comment by systopia** [comment]
@tttp Could you confirm that the fix above works for you? If this was indeed the problem it should've mapped any potential cycle day before the 10th to the 1st.

**Comment by systopia** [comment]
@Fabian-SYSTOPIA has tested this positively

**Comment by systopia** [comment]
released with 1.2.5.beta2

**Comment by tttp** [comment]
Actually, the problem we experienced is similar, but related to the API (it defaults to 1, it should default to the first available cycle_das + notice + buffer, as the PP does)

@scardinius, can you update the API to act accordingly?

(context: we are developping a new donation interface that pushes the donations to civi via the api)
