### ISSUE TITLE
Menu item (CiviSEPA Dashboard ) not showing in menu (drupal).

### ISSUE THREAD

**Issue by jvos** [Project60/org.project60.sepa#450]
The menu item "CiviSEPA Dashboard" is not showing in the Contributions menu, while the user has the permission "CiviContribute: access CiviContribute" (in Drupal).
The menu item is visible if you give the user the permission "CiviCRM: administer CiviCRM"

**Comment by DanielvV** [comment]
Created a pull request. Let's see what the maintainers (@systopia, @tttp) of this extension think of this.

**Comment by jvos** [comment]
Thanks for the pull request, i'm curious !

**Comment by systopia** [comment]
If it's o.k. with you guys, I'll not "fix" this and wait for #243 to be fully tested - I don't want to cause confusion with the users twice...

@DanielvV / @jvos  Would you be able to help test #243?
