### ISSUE TITLE
`CRM_Core_OptionGroup::getValue()` is deprecated

### ISSUE THREAD

**Issue by DanielvV** [Project60/org.project60.sepa#455]
Gives warning in log:
```
Oct 03 17:47:06  [warning] Deprecated function, use CRM_Core_PseudoConstant::getKey
Array
(
    [civi.tag] => deprecated
)
```
See civicrm-core [CRM/Core/OptionGroup.php#L375-L423](https://github.com/civicrm/civicrm-core/blob/master/CRM/Core/OptionGroup.php#L375-L423)
Documentation: https://docs.civicrm.org/dev/en/master/framework/pseudoconstant/

**Comment by systopia** [comment]
Thanks for pointing it out. PRs welcome :)

**Comment by DanielvV** [comment]
Its already there: #454 :)

**Comment by systopia** [comment]
@DanielvV I knew I forgot something :) Thanks a lot, it's merged
