### ISSUE TITLE
Postal address required for Swiss mandates

### ISSUE THREAD

**Issue by psampont** [Project60/org.project60.sepa#462]
Since January 2018, our bank (ING) ask to add a postal address in SEPA file for Swiss mandates.
Are there other people with the same problem with other banks?

Currently we need to add the mention manually in the Telelink software of the bank.

**Comment by systopia** [comment]
Thanks @psampont. 

I'm not sure if this is the rule for all of Switzerland or just your bank, but Switzerland is not a "full" SEPA country anyway, and they are known to have some quirks in their implementation.

I would suggest that you set up some custom checking in your system to make sure every contact with a Swiss SEPA mandate has a proper postal address. I think it's unlikely that we'll include that into CiviSEPA any time soon.

**Comment by Detsieber** [comment]
I already heard that since last year, the SEPA regulations require a
postal address when debiting Swiss mandates.

We have at our organisation (Digitalcourage) a small number of SEPA
mandates from Swiss donators, but fortunately they were processed in the
past without problems.
However, since CiviSEPA should comply with current regulations, it would
be helpful to do an update to the extension.

I could imagine the Software für Engagierte e.V. could step in for funding!


Best
Detlev


Am 09.01.2018 um 11:55 schrieb Philippe SAMPONT:

**Comment by systopia** [comment]
We created the "pain.008.003.02 (EBICS-3.0 RCUR/CH)" format in the current ``master``, that does two things:
* all transactions will be exported as ``RCUR``
* Swiss IBANs will trigger adding the address to the file

@psampont Could you test it? Be careful, the ``master`` branch has a lot of changes that have not been tested well.

**Comment by psampont** [comment]
Thanks. It seems to work. The Swiss mandate has been exported with his address.
But, actually, I can't test it in production with the bank.

PS. After the update, the parameter PAIN Version of my bank has become empty. Whereas before, he was at PAIN.008.001.02 (CDD EBICS-3.0) So, It may be necessary to review the update procedure to not lose this value.

**Comment by systopia** [comment]
> Thanks. It seems to work. The Swiss mandate has been exported with his address.
But, actually, I can't test it in production with the bank.

That's good to hear, thanks for checking.

> PS. After the update, the parameter PAIN Version of my bank has become empty. Whereas before, he was at PAIN.008.001.02 (CDD EBICS-3.0) So, It may be necessary to review the update procedure to not lose this value.

@psampont : I'm not quite sure which parameter you mean, could you be more specific? Are you talking about the file or the creditor settings? Or something else?

**Comment by psampont** [comment]
> @psampont : I'm not quite sure which parameter you mean, could you be more specific? Are you talking about the file or the creditor settings? Or something else?

I was talking about the parameter 'Pain Version' in 'Add/Edit Creditor' : 'Creditor Information' in page https://localhost/civicrm/admin/setting/sepa

**Comment by systopia** [comment]
Ah, I see. The problem was, that 'PAIN.008.001.02 (CDD EBICS-3.0)' and 'pain.008.003.02 (COR1 EBICS-3.0)' were identical, so I disabled one of them. That was probably the one you used...

@psampont Does that make sense?

**Comment by psampont** [comment]
Yes. No problem.

But, if 'PAIN.008.001.02 (CDD EBICS-3.0)' is disabled, the Pain Version field should be adapted to the creditors database during the upgrade.

**Comment by Detsieber** [comment]
Do I understand correctly, that this is only implemented with "master", but not with "1.2.6 beta1"?

If so, when will that feature be released?

**Comment by systopia** [comment]
This will not be released with the ``1.2`` branch, because it relies on infrastructure only available in ``1.4``. However, I'm very hopeful that we can release an alpha version of ``1.4`` very soon.

**Comment by systopia** [comment]
I added the new format "pain.008.003.02 with Address (EBICS-3.0)" with ``1.4``
