### ISSUE TITLE
Empty payment processor field after cloning or manual adding mandate

### ISSUE THREAD

**Issue by scardinius** [Project60/org.project60.sepa#463]
Hi,

in some cases payment processor of civicrm_contribution_recur is empty.

When mandates derived from contribution page, then everything is fine, civicrm_contribution_recur has payment processor.

In opposite, we have two cases when payment processor is empty:

1. cloning existing valid mandate
    * cloned mandate should have the same payment processor
2. adding new mandate by using button `Record SEPA contribution`
    * new mandate should have payment processor of type `SEPA_Direct_Debit`.

What do you think?

**Comment by scardinius** [comment]
I thought about it again and this indeed is not a error. "Manual" means not automatic, not by payment processor.

**Comment by scardinius** [comment]
I'd like to reopen this issue. I found out that `civicrm_sdd_creditor` already has field `payment_processor_id` but it is not used. @tttp Is there a plan to use it?

How it could work:

* possibility to set up payment processor at creditor setting page. For testing creditors, it should be only testing payment processor. The same for production creditors/processors
* add setting payment_processor_id based on creditor configuration
    * at api SepaMandate.createfull
    * at CRM_Sepa_Page_CreateMandate->createMandate() method

**Comment by jensschuppe** [comment]
Payment processors have moved to separate extension(s), please file an issue there if this is still relevant.
