### ISSUE TITLE
In progress status for One-Off is not compatible with CiviCRM assumptions

### ISSUE THREAD

**Issue by scardinius** [Project60/org.project60.sepa#464]
Hi,

As you known SEPA set for One-Off contribution an `In progress` status. This means that it's not possible to find such contributions at `Find Contribution` civicrm/contribute/search?reset=1

https://github.com/civicrm/civicrm-core/blob/eaf5d8e7f0dcd45c46d501a701194c75d3187dd6/CRM/Contribute/BAO/Query.php#L943

```php
// Remove status values that are only used for recurring contributions or pledges (In Progress, Overdue).
unset($statusValues['5'], $statusValues['6']);
```

@tttp I see two solutions:

1. change SEPA behavior or 
2. change CiviCRM assumptions

What do you think?

**Comment by systopia** [comment]
@scardinius I'd prefer to "change CiviCRM assumptions". I'll ask Tim...

**Comment by tttp** [comment]
I did a pr to civicore

**Comment by tttp** [comment]
PR pushed, discussion ongoing https://github.com/civicrm/civicrm-core/pull/11640

**Comment by systopia** [comment]
It's merged :)
