### ISSUE TITLE
Invalid SQL query in prepareCreateForm(): for SELECT DISTINCT, ORDER BY expressions must appear in select list

### ISSUE THREAD

**Issue by jensschuppe** [Project60/org.project60.sepa#472]
The MySQL query defined in CRM/Sepa/Page/CreateMandate.php:239 is invalid for MySQL with ONLY_FULL_GROUP_BY, and for other SQL dialects as well:

```sql
SELECT DISTINCT iban, bic FROM civicrm_sdd_mandate WHERE contact_id=$contact_id ORDER BY creation_date DESC;
```
This causes the mandate form (e.g. for adding a mandate for a contact) not opening.

Including the ORDER BY field `creation_date` in the SELECT clause appears to solve the problem without side effects:

```sql
SELECT DISTINCT iban, bic, creation_date FROM civicrm_sdd_mandate WHERE contact_id=$contact_id ORDER BY creation_date DESC;
```

**Comment by rthouvenin** [comment]
Noticed the same problem in our setup today after upgrading. It's quite serious as this prevents our staff from manually recording SEPA donations.

**Comment by scardinius** [comment]
It's enough to update query to this one:

```sql
SELECT DISTINCT creation_date, iban, bic, creation_date FROM civicrm_sdd_mandate WHERE contact_id=$contact_id ORDER BY creation_date DESC;
```
