### ISSUE TITLE
Cancelling mandate doesn't remove contributions on status In progress from active batch

### ISSUE THREAD

**Issue by scardinius** [Project60/org.project60.sepa#478]
Hi,

This case occurs when you cancel mandate which already has a contribution in active batch. And when contribution has `In Progress` status. The problem is that SEPA searches for only Pending contributions

I prepared #476 PR which use Pending and In Progress statuses.

**Comment by systopia** [comment]
This is by design. Status ``In Progress`` means (in CiviSEPA) that the contribution has already been sent to the bank, hence it cannot be recalled any more.

@scardinius: Does that answer the question?
