### ISSUE TITLE
Check for "navID" being set in CRM_Utils_SepaMenuTools::getMaxNavID()

### ISSUE THREAD

**Issue by jensschuppe** [Project60/org.project60.sepa#486]
PHP notices "Undefined index: navID in CRM_Utils_SepaMenuTools::getMaxNavID()" are being thrown while crawling the menu tree for finding the maximum "navID" for  items in the navigation menu tree when there are menu items without a "navID" set.

Not sure whether this stems from incorrect implementations in other extensions (i.e. them not setting a "navID" attribute for a menu item), but it's quite annoying when this happens.

There should be a check for whether the "navID" attribute exists in `CRM_Utils_SepaMenuTools::getMaxNavID()` within `$max_id = max($max_id, $entry['attributes']['navID']);`, e.g. `    $max_id = (isset($entry['attributes']['navID']) ? max($max_id, $entry['attributes']['navID']) : 0);`.

**Comment by systopia** [comment]
PRs welcome :)

**Comment by systopia** [comment]
Pulled and fixed with https://github.com/Project60/org.project60.sepa/commit/a60f3c0c80a4ad35a23a515ec36755663f391a63, will be released with ``1.4``
