### ISSUE TITLE
Record SEPA Contribution button dissapears on tab switching

### ISSUE THREAD

**Issue by francescbassas** [Project60/org.project60.sepa#487]
Steps to reproduce:

1. Load a contact summary page
2. Switch to contribution tab (Record SEPA Contribution button appears correctly)
![first_tab_visualization](https://user-images.githubusercontent.com/1064675/39807247-1a592e86-537c-11e8-9e9f-ed53df055633.png)

3. Switch to any other tab

4. Return to contribution tab (Record SEPA Contribution button it is not there anymore
![second_tab_visualization](https://user-images.githubusercontent.com/1064675/39807252-1f515d3c-537c-11e8-8164-191cd2fbe67e.png)

I'm testing SEPA Direct Debit Module on a CiviCRM 4.7.22 environment.

**Comment by francescbassas** [comment]
Looking at [Summary.sepa.tpl](https://github.com/Project60/org.project60.sepa/blob/1.2.5/templates/CRM/Contact/Page/View/Summary.sepa.tpl) I can see on [line 46](https://github.com/Project60/org.project60.sepa/blob/1.2.5/templates/CRM/Contact/Page/View/Summary.sepa.tpl#L46):

    contribution_snippet_changed = true; // important to do this BEFORE changing the model

In previous versions maybe it worked but now seems that clicking contribution tab reloads all it's content.

Maybe the function [sepa_modify_summary_tab_contribution](https://github.com/Project60/org.project60.sepa/blob/1.2.5/templates/CRM/Contact/Page/View/Summary.sepa.tpl#L28) would be called every time and only when contribution tab is clicked.

It is also a good oportunity to optimize code. I have noticed that `sepa_modify_summary_tab_contribution` is massively called due to listener defined on [line 25](https://github.com/Project60/org.project60.sepa/blob/1.2.5/templates/CRM/Contact/Page/View/Summary.sepa.tpl#L25):

    cj("#mainTabContainer").bind("DOMSubtreeModified", sepa_modify_summary_tab_contribution);

**Comment by francescbassas** [comment]
@systopia, has anyone else come across this problem?

**Comment by francescbassas** [comment]
Seems related with https://github.com/Project60/org.project60.sepa/issues/405

**Comment by systopia** [comment]
> @systopia, has anyone else come across this problem?

Yes, but it won't be fixed, since this will be obsolete with ``1.4`` where SEPA has it's own tab.

**Comment by francescbassas** [comment]
Great @systopia.

Please consider that probably `sepa_modify_summary_tab_contribution` is still massively called due to listener in `/templates/CRM/Contact/Page/View/Summary.sepa.tpl`:

`cj("#mainTabContainer").bind("DOMSubtreeModified", sepa_modify_summary_tab_contribution);`

It should only be called when mandate tab is clicked. Do we open an other issue?

**Comment by systopia** [comment]
Thanks @francescbassas.

> Please consider that probably sepa_modify_summary_tab_contribution is still massively called due to listener in /templates/CRM/Contact/Page/View/Summary.sepa.tpl:

I know, we still want to mark the SEPA mandates in the recurring contributions list, so they don't get confused with "normal" recurring contributions.

> It should only be called when mandate tab is clicked. Do we open an other issue?

Go ahead, there is definitely room for optimisation.
