### ISSUE TITLE
Flexible mandate links

### ISSUE THREAD

**Issue by systopia** [Project60/org.project60.sepa#501]
We would like to add a new link structure linking ``civicrm_sdd_mandate`` to any number of entities (entity_id/entity_table).

**Comment by tttp** [comment]
What is the use case of sharing the mandates between several entities?

**Comment by systopia** [comment]
> What is the use case of sharing the mandates between several entities?

Well, I was thinking of using this link for different aspects, e.g. class ``REPLACE`` to link to another mandate that is being replaced by a new one (e.g. due to bank account changes). At the same time, I plan on linking mandates to e.g. memberships. So here there's already two links for the same mandate at the same time - but with different classes.

But there might be even more. If a mandate was linked to one membership, and then later to another, there might even be multiple links of the same class. For this, I'm adding the optional fields ``is_active``, ``start_date`` and ``end_date`` to the data structure.

**Comment by systopia** [comment]
First draft will be in ``1.4``
