### ISSUE TITLE
Signature date changes to current date on any update

### ISSUE THREAD

**Issue by patf** [Project60/org.project60.sepa#513]
The signature date (`civicrm_sdd_mandate.date`) is changed to the current date whenever a mandate is updated. This behaviour can be reproduced with an API call to `SepaMandate.create` with `id={existing_mandate_id}`.

For recurring mandates that means the signature date will be updated to the current date during the first debit (when the mandate status is updated from FRST to RCUR).

I was able to reproduce this on master, 1.2.5 and 1.2.6.beta2.

**Comment by systopia** [comment]
@patf Thanks for reporting! Could you please verify that https://github.com/Project60/org.project60.sepa/commit/ce876399df9adc6b9e6b9f8168c71a4b81a77d27 fixes it?

**Comment by systopia** [comment]
@patf thanks.

will be released with ``1.4.alpha2``
