### ISSUE TITLE
l10n on transifex

### ISSUE THREAD

**Issue by bjendres** [Project60/org.project60.sepa#519]
See https://lab.civicrm.org/dev/translation/issues/10

**Comment by masetto** [comment]
Hi, I don't understand if this project will be joined on Transifex or not. Now Transifex is surely not up to date.

**Comment by bjendres** [comment]
Feel free to upload the current ``sepa/pot`` file to transifex, along with the current translations. I never figured out how to do that...

**Comment by mlutfy** [comment]
Translations are here : https://www.transifex.com/civicrm/civicrm_extensions/sepa/

Note that there is an older CiviSepa on Transifex, which will be deleted.

**Comment by eptbertram** [comment]
There are some strings in Transifex project "CiviSEPA (Old, will be deleted soon)" https://www.transifex.com/civicrm/civicrm_extensions/civisepa/, which aren't in project "sepa" https://www.transifex.com/civicrm/civicrm_extensions/sepa/. 

Related to https://github.com/Project60/org.project60.sepa/issues/647 ?

**Comment by bjendres** [comment]
I'm not sure who created those, and who's maintaining them. I usually just publish the the l10n contained in this repository with the release. 

But that shouldn't be in the way of replacing it with the one generated with transifex on your system.

**Comment by eptbertram** [comment]
u r right. de_DE is contained in this repo. 

Transifex shows 100% translation for fr_FR and nl_NL (and big efforts for Polish, Spanish and Japanese [they don't even use SEPA in JP]), too. These translations can be copied from Transifex into the local l10n directory of the extension if needed, e.g. with extension https://github.com/cividesk/com.cividesk.l10n.update 

Maybe you like to close this issue? There is a solution and "sepa" is on Transifex, too (someone did this: https://lab.civicrm.org/dev/translation/-/wikis/extension-translation#publishing-extensions-on-transifex ).

**Comment by comradekingu** [comment]
https://hosted.weblate.org/hosting/

**Comment by bjendres** [comment]
Closing this with the merge of #652
