### ISSUE TITLE
xml-files with address (pain.008.003.02 with Address (EBICS-3.0)) should be filtered for valid characters

### ISSUE THREAD

**Issue by Detsieber** [Project60/org.project60.sepa#520]
As a solution for #462, an new pain format was introduced: pain.008.003.02 with Address (EBICS-3.0)

Unfortunately, if the address contains special characters (which happens often e.g. for french street names), the bank system crashes... (this happens with the "Bank für Sozialwirtschaft", I am not aware if other Banks are affected as well).

Anyhow, there should be a filter, that makes sure only "allowed characters" (as defined by the SEPA standard) are written to any fields within the xml file:

   "Zulässiger SEPA Zeichensatz im DFÜ Abkommen (Deutsche Kreditwirtschaft)"

 a                     - z | a                     b c d e f g h i j k l m n o p q r s t u v w x y z
A - Z | A B C D E F G H I J K L M N O P Q R S T U V W X Y Z
0 - 9 | 0                     1 2 3 4 5 6 7 8 9
Sonderzeichen | /                      ? : ( ) . , ' + -
Leerzeichen | Space

**Comment by systopia** [comment]
Thanks for reporting, @Detsieber. We'll see if we can find some funding for this...
