### ISSUE TITLE
My PhpStorm does not like this statement and it does not seem right?

### ISSUE THREAD

**Issue by ErikHommel** [Project60/org.project60.sepa#521]
In my PhpStorm I get an error on this statement:
`    $contrib = $bao->getContract();`

in CRM_Sepa_BAO_SEPAMandate->getUnbatchedContributionIds.
I can see why it does because $bao is not defined nor is it a param. I actually think it should be:

`$contrib = $this->getContract();`

but I might be missing something?

**Comment by systopia** [comment]
No, you're absolutely right. This code path, however, was not used any more, and the function had already been deprecated.

I fixed it anyway, so PhpStorm is happy :)

Thanks for reporting and a happy new year!
