### ISSUE TITLE
Automatically create bank account in CiviBanking

### ISSUE THREAD

**Issue by adanielvv** [Project60/org.project60.sepa#528]
If you create a SEPA mandate, the bank account could be saved in CiviBanking.
See https://github.com/Project60/org.project60.sepa/compare/master...adanielvv:dev_fix_bank_account_propagation
Code should be added to check if CiviBanking is installed.
(There are also some changes here that pick up the bank account if there is no BIC)

**Comment by bjendres** [comment]
Good idea, but I think this would be better placed in a SepaMandate post hook implemented by CiviBanking. Don't you think?

**Comment by adanielvv** [comment]
Yep, above link to branch was just a quick hack. Is not in production any more. (I could not implement a better solution in time before I had to transfer the management of the IT infra, incl. CiviCRM, to another company.) Nice to hear from you btw! I have moved to the other side of the ocean.

**Comment by bjendres** [comment]
Thanks @adanielvv!

> I have moved to the other side of the ocean.

To the americas, or somwhere else? Greetings anyway!
