### ISSUE TITLE
SDD PP workflow error can never be thrown

### ISSUE THREAD

**Issue by jensschuppe** [Project60/org.project60.sepa#533]
This code https://github.com/Project60/org.project60.sepa/blob/1a83ccf6b6afa12670aa1218a0a096521b3a8f0f/CRM/Core/Payment/SDDNG.php#L197-L201 seems bogus, the "SDD PP workflow error" error can never be thrown due to self-comparison of `$contribution_id`.

Is this relevant for anything?

**Comment by bjendres** [comment]
Will be fixed in https://github.com/Project60/org.project60.sepapp
