### ISSUE TITLE
Introduce IBAN Blacklist

### ISSUE THREAD

**Issue by bjendres** [Project60/org.project60.sepa#540]
In some cases (e.g. fraud) it's handy to maintain an IBAN blacklist (as an option group). IBANs in that list would not validate.

**Comment by bjendres** [comment]
Will be released with ``1.5``

**Comment by blipp** [comment]
This seems like a very useful feature, thanks! Please consider renaming blacklist to blocklist. See https://github.com/Chocobozzz/PeerTube/issues/2790 for a similar discussion.

**Comment by bjendres** [comment]
> Please consider renaming blacklist to blocklist.

That sounds like a very good idea.
