### ISSUE TITLE
Truncated date in the SepaMandate createfull API

### ISSUE THREAD

**Issue by psampont** [Project60/org.project60.sepa#553]
Since CiviSEPA 1.4, the dates: date and validation_date are truncated in the civicrm_api3_sepa_mandate_createfull function.
The mandate created with 'date' => 20191114202959 is saved with the value "date": "2019111400000000".

**Comment by psampont** [comment]
I think the mistake comes from this line: 
`    $create_mandate = $create_contribution; // copy array`

We will send a PR soon.

**Comment by bjendres** [comment]
Thanks @psampont, will be released with ``1.5``
