### ISSUE TITLE
Add "create mandate" and "terminate mandate" actions for action-provider

### ISSUE THREAD

**Issue by bjendres** [Project60/org.project60.sepa#554]
Offer "create mandate" and "terminate mandate" for @jaapjansma's "action-provider extension":https://lab.civicrm.org/extensions/action-provider

**Comment by jaapjansma** [comment]
Nice

**Comment by jensschuppe** [comment]
9d9915eaede9085339e22b4330d035f4aa6cb5b0 checks for the class itself being existent. This is neccessary when upgrading the extension and the psr4 classloader info not yet being read from the `info.xml` file, resulting in a fatal without the possibility to update extension information.

**Comment by bjendres** [comment]
Will be released with ``1.5``
