### ISSUE TITLE
API to terminate SepaMandate never throws an error

### ISSUE THREAD

**Issue by BenediktMagnus** [Project60/org.project60.sepa#562]
The API to terminate a SepaMandate (`civicrm_api3_sepa_mandate_terminate`) never throws an API error, even if the termination is not successful.

This is the case because `civicrm_api3_create_success` is returned regardless of the result of `CRM_Sepa_BAO_SEPAMandate::terminateMandate`, which would, if the termination fails, return `false`.

This issue is fixed in db4d43ce75ef4be6bb2f6b84cab12eb13bc6b011 (branch dev_469, in the context of automated tests #469) but not merged yet and should be handled separately.

**Comment by bjendres** [comment]
Will be released with ``1.5``
