### ISSUE TITLE
SEPA NG Payment Processor: Error when price set contains a line with amount = 0.00

### ISSUE THREAD

**Issue by Detsieber** [Project60/org.project60.sepa#565]
We have an event registration with a price set, where one option is free (amount=0.00), whereas another option is payable.

With the NG payment processor, CiviCRM throws an error:

> Sorry, due to an error, we are unable to fulfill your request at the moment. You may want to contact your administrator or service provider with more details about what action you were performing when this occurred.
> Expected one Contribution but found 25

The "old" payment processor works fine, as well as the PayPal payment processor.

CiviCRM: 5.19.4 on Wordpress, CiviSEPA: 1.4

**Comment by bjendres** [comment]
The whole payment processor has been a continuous PITA, so with ``1.5`` we'll move the payment processor code into a separate extension. This way, you can install and use the flavour of SEPA payment processor that works for *you*.

**Comment by bjendres** [comment]
With CiviSEPA ``1.5`` we're moving the payment processors to the [SEPA PP](https://github.com/Project60/org.project60.sepapp) extension.

@Detsieber please move this ticket there and close it here.

**Comment by Detsieber** [comment]
Moved to the SEPA PP extension:
https://github.com/Project60/org.project60.sepapp/issues/1

**Comment by bjendres** [comment]
@Detsieber thanks.
