### ISSUE TITLE
Missing download link after upgrade to 1.4

### ISSUE THREAD

**Issue by irritatie** [Project60/org.project60.sepa#567]
After upgrading org.project60.sepa from 1.2.5 to 1.4, the link where you would normally download your bank file XML is gone. 

CiviCRM gives the following error. 
"Error
Cannot load for group #127.
Error was: Class format file '' not found."

**Comment by irritatie** [comment]
This can be fixed by going to the Creditor settings, select a new file format, and save. This is an extra option that needs to be filled in, or the link doesn't work. (Thanks Björn)

**Comment by jensschuppe** [comment]
Please check your creditor settings. The format `pain.008.003.02 (CDD EBICS-3.0)` was replaced by `pain.008.003.02 (COR1 EBICS-3.0)`, so you would have to adjust your configuration to use this format instead. The error appears because the old format (option value) has been disabled

**Comment by irritatie** [comment]
Thanks, you're incredibliy quick to answer. I just posted this here so that people could find the solution somewhere :-)

Issue is closed, no problem if you know where to look.
