### ISSUE TITLE
SEPA Mandate incorrect via Webforms

### ISSUE THREAD

**Issue by sluc23** [Project60/org.project60.sepa#579]
*(Drupal 7.71 / CiviCRM 5.24.4 / Webform 4.22 / Webform_Civicrm 4.28 / CiviSepa 1.5-alpha7)*

Using Webforms the create new Contacts and SEPA payment method for recurring payments, after submitting the webform, the SEPA Mandate it's not properly created.
Before digging more into the issue, I couldn't find any documentation about how to configure CiviSEPA for Webforms

Is CiviSEPA ready to work with webform integration?

**Comment by bjendres** [comment]
I assume you're talking about Coleman's webform integration, and not payment processors, right? I have never tried that myself, I don't even know how it works. 

Anybody else here who uses this kind of setup?

**Comment by bjendres** [comment]
@sluc23 should I close this? How did you deal with this in the end?

**Comment by sluc23** [comment]
yes, closing.. don't really remember what happened :P !
