### ISSUE TITLE
Array to string conversion in SettingsMetadata.php

### ISSUE THREAD

**Issue by wikimas** [Project60/org.project60.sepa#583]
I've just installe CiviSEPa and I get a lot of 
Notice: Array to string conversion in Civi\Core\SettingsMetadata::_filterSettingsSpecification() (line 133 of /htdocs/civi/sites/all/modules/civicrm/Civi/Core/SettingsMetadata.php). - notices.

Not sure if I should be worried?

**Comment by bjendres** [comment]
> Not sure if I should be worried?

I don't think so. CiviCRM Core changed the handling of the settings in one of the more recent versions, and that triggers notices that hadn't been there before. As far as I know this doesn't affect functionality. 

On a production site, you can simply suppress PHP notices, which usually don't cause any harm.

It would be nice to change the code to not produce the notice any more, but frankly it's not our most pressing issue.

**Comment by wikimas** [comment]
Thats fine, just what I wanted to hear!

**Comment by bjendres** [comment]
released with ``1.5``
