### ISSUE TITLE
PAIN file format 008.001.02 not standards-compliant

### ISSUE THREAD

**Issue by jensschuppe** [Project60/org.project60.sepa#589]
The `pain_008_001_02` template does not seem to be standards compliant regarding the following section:

```xml
<CdtrSchmeId>
  <Nm>{$creditor.name}</Nm>
  <Id>
    <PrvtId>
      <Othr>
        <Id>{$creditor.identifier}</Id>
        <SchmeNm>
          <Prtry>SEPA</Prtry>
        </SchmeNm>
      </Othr>
    </PrvtId>
  </Id>
</CdtrSchmeId>
```

A validating bank claims the following error:
> Unexpected element "Nm" from the namespace "urn:iso:std:iso:20022:tech:xsd:pain.008.001.02".

The specification's example implementation [here](https://www.ebics.de/fileadmin/unsecured/anlage3/anlage3_bsp/pain.008.001.02.xml) ([Overview page](https://www.ebics.de/de/datenformate/ergaenzende-dokumente)) does not include such an element at that position.

The element should thus be removed from the template, I guess.

@bjendres what do you think?

**Comment by tttp** [comment]
According to this xsd, your bank is wrong and civisepa is right

https://wiki.xmldation.com/@api/deki/files/671/=pain.008.001.02.xsd

    <xs:complexType name="PartyIdentification32">
        <xs:sequence>
            <xs:element maxOccurs="1" minOccurs="0" name="Nm"
type="Max140Text"/>
            <xs:element maxOccurs="1" minOccurs="0" name="PstlAdr"
type="PostalAddress6"/>
            <xs:element maxOccurs="1" minOccurs="0" name="Id"
type="Party6Choice"/>
            <xs:element maxOccurs="1" minOccurs="0" name="CtryOfRes"
type="CountryCode"/>
            <xs:element maxOccurs="1" minOccurs="0" name="CtctDtls"
type="ContactDetails2"/>
        </xs:sequence>
    </xs:complexType>

**Comment by jensschuppe** [comment]
@tttp Thanks, that's indeed correct. Should've checked the schema before. The official XSD file can be downloaded here: https://www.iso20022.org/message/14451/download.

**Comment by wintermoor** [comment]
GLS (and maybe other Volksbanken in Germany) have this issue, too. 

Deleting line 44 in SEPA-xml manually will help. To get this fixed in CiviSEPA, please delete line 32 in transaction-details.tpl at /civicrm/ext/org.project60.sepa/templates/Sepa/Formats/pain_008_001_02_OTHERID  (Create a new file format for this, because otherwise an update will erase it.)
