### ISSUE TITLE
Cannot install in CiviCRM 5.29.0

### ISSUE THREAD

**Issue by TheAssassin** [Project60/org.project60.sepa#593]
In the last three days, I've been evaluating CiviCRM for a local association. So far, it looks pretty good. As the association resides in Germany, SEPA integration would be great to have to help automate membership fees' debit transfers etc. Unfortunately, I cannot find out how to install this extension.

I've got two test systems now. The first instance runs Backdrop CMS. Installing CiviCRM was not an issue at all, it's running fine. The suggested installation via the extensions catalog doesn't work for my instance, the extension doesn't even show up. I tried to install the extension manually but to no avail, it doesn't show up in CiviCRM.

I guessed it might be a compatibility issue, so I set up a second site with Drupal 8. The same issues can be found here, though.

Is the extension even compatible with my CiviCRM version? As far as I understand CiviCRM's extension system, an extension that e.g., supports 5.5 should run on 5.29 as well. If it is compatible, what could be the reason it doesn't show up in the extensions catalog?

I'm really lost right now, running out of ideas how to get the extension to finally run...

**Comment by Detsieber** [comment]
CiviSEPA should be fully compatible with CiviCRM 5.29.

One hint: Did you set the permissions for the extension within the Drupal permissions? This often causes that kind of problems...
Remember: Drupal doesn't automatically give permission for everything to the administrator user, you have to take care for that by yourself!

**Comment by TheAssassin** [comment]
I think I'd first have to be able to install the extension before worrying about preferences. The [install guide](https://docs.civicrm.org/civisepa/en/latest/#installation) also doesn't mention any permissions. But I'll have a look quickly in the Backdrop install. Do you have a list which permissions I need to grant?

**Comment by TheAssassin** [comment]
Just retried a manual installation, this time it seems to have worked. But my initial question still remains unanswered: is it normal that the extension doesn't show up in that catalog? The official installation instructions only show how to install the extension this way, not how it's done manually.

**Comment by bjendres** [comment]
> is it normal that the extension doesn't show up in that catalog?

The extension is listed in the [extension directory](https://civicrm.org/extensions), but it's not listed among the relatively short list of extensions that have been 'reviewed' for in-app installment. The number of extension in the directory is a lot higher (>400) and the number of CiviCRM extensions out there in general would be much higher still.

The number of 'reviewed' extensions used to be very short, but there's recently been a push to add more. Feel free to suggest this extension as well :)

**Comment by TheAssassin** [comment]
> The extension is listed in the extension directory, but it's not listed among the relatively short list of extensions that have been 'reviewed' for in-app installment.

I see. I was already wondering why the list was so short. The [docs]() however suggest that the extension should be available there already:

> ### Installation
> 
> Use the following steps to install CiviSEPA. * Administer > System Settings > Extensions * Add New * Find, download, and install

"Find, download and install" is misleading. I would suggest to refine this section in the docs.

**Comment by bjendres** [comment]
Hm, it does also say
> Important: Please download a official release! 

and links to the GitHub downloads. Nevertheless you're right, this should be more clear.

@TheAssassin, would you care to suggest a change and create a PR?

**Comment by TheAssassin** [comment]
Done.

**Comment by bjendres** [comment]
Thanks @TheAssassin
