### ISSUE TITLE
Erroneous German translation for "Edit SEPA mandates" permission

### ISSUE THREAD

**Issue by jensschuppe** [Project60/org.project60.sepa#596]
See https://github.com/Project60/org.project60.sepa/blob/2658808765eca75d53f8864cbc63707be9e0b73e/l10n/de_DE/LC_MESSAGES/sepa.po#L1368-L1370

This should be `SEPA-Mandate bearbeiten`

**Comment by bjendres** [comment]
released with ``1.5``
