### ISSUE TITLE
CBI File Format (was: Validation error on import XML to my bank)

### ISSUE THREAD

**Issue by masetto** [Project60/org.project60.sepa#601]
Hi,
I state that this is the first time I create XML file from this module. 😄 

XML file starts with this rows:
```
<?xml version="1.0" encoding="UTF-8"?>
<Document xmlns="urn:iso:std:iso:20022:tech:xsd:pain.008.001.02" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="urn:iso:std:iso:20022:tech:xsd:pain.008.001.02 pain.008.001.02.xsd">
  <CstmrDrctDbtInitn>
    <GrpHdr>
```

When I import to my internet banking (Italian bank) I have this error:
![2020-10-09_17h18_23](https://user-images.githubusercontent.com/9961202/95603169-348c3080-0a56-11eb-805f-3b07c66dcde7.png)

File `pain.008.001.02.xsd` does not exist.

Is this a problem of my bank or another one?
Thanks

**Comment by bjendres** [comment]
@masetto You can either

1. talk to your bank and ask which SEPA PAIN flavours they accept, or
2. try all the formats that CiviSEPA is shipped with, and see if any gets accepted.

**Comment by masetto** [comment]
Hi @bjendres,
this is the answer of my bank:

> streams starting with the `<Document` tag are NOT accepted by the system, they must be CBI -> CBIBdySDDReq compliant
> In this case it is NOT enough to modify the start tag, the flow must be created respecting the CBI rules.

What is this standard? Is it different from the ones you have implemented?
Thanks

**Comment by bjendres** [comment]
I'm not aware of anyone having implemented these CBI file formats for CiviSEPA. 

The process of doing this would probably be something like:

1. check if the data and the workflows in CiviSEPA can be mapped to that file format. If so:
2. create a new file format (see e.g. [HERE](https://github.com/Project60/org.project60.sepa/tree/master/templates/Sepa/Formats) and [HERE](https://github.com/Project60/org.project60.sepa/blob/master/templates/Sepa/Formats/readme.txt))
3. create a PR to add the new file format to CiviSEPA. Alternatively, this could be part of an extension, see e.g. [HERE](https://github.com/systopia/de.systopia.esr/tree/master/templates/Sepa/Formats/ta875)

**Comment by masetto** [comment]
Hi @bjendres 
thank you for your indications. [This is an example](https://github.com/Project60/org.project60.sepa/files/5370573/SepaDirectDebit-example-xml.txt) XML CBI file accepted by my italian bank.
Is it a format you have already heard of? I think it is a standard in Italy. Do you think it is useful to develop it in this CiviSEPA extension?

**Comment by bjendres** [comment]
> Is it a format you have already heard of? I think it is a standard in Italy. 

No, never come across it, sorry.

> Do you think it is useful to develop it in this CiviSEPA extension?

If it's an Italian standard, probably. Would you want to do it yourself, or would you want to hire us to do it?

**Comment by masetto** [comment]
I'll try it by myself, thanks.

**Comment by bjendres** [comment]
@masetto Did you ever manage to create this file format in CiviSEPA? If so, could you create a PR with this? Other people might want to use that, too...

**Comment by masetto** [comment]
:+1: @bjendres, I will continue this shortly

**Comment by masetto** [comment]
@bjendres can you give me some instructions for transferring sepa mandates to CiviCRM. What are the steps to be taken?
Thank you

**Comment by bjendres** [comment]
You can use the APIv3 using the ``SepaMandate.createfull`` action. 

Alternatively, you could use a formprocessor, CiviSEPA offers a couple of actions around SEPA mandates.

(Sorry for the late reply. )
