### ISSUE TITLE
5.31 compatibility: Tab "SEPA mandates" on contact summary does not appear

### ISSUE THREAD

**Issue by Detsieber** [Project60/org.project60.sepa#603]
The tab is not shown on the contact summary, after upgrade to CiviCRM 5.31.0

The functionality is still available via url:
Drupal8: ../civicrm/sepa/tab?reset=1&snippet=1&force=1&cid=3134
Wordpress: .../wp-admin/admin.php?page=CiviCRM&q=civicrm%2Fsepa%2Ftab&reset=1&snippet=1&force=1&cid=11

But, the tab is lost.

It seems, that the technique used to inject the tab into the contact summary broke with the UI changes in CiviCRM 5.31

Hint: The siimilar issue happens for the donrec extension, that probably uses the same mechanism.

**Comment by bjendres** [comment]
I think this should be fixed.

@Detsieber Could you verify that it works with ``1.5-beta2``? 

Caution: ``1.5-beta2`` will remove the payment processors, please use a test environment.

**Comment by Detsieber** [comment]
YESSS - with 1.5-beta2, the tab "SEPA mandates" is displayed again!


Am 12.11.20 um 09:43 schrieb Björn Endres:

**Comment by bjendres** [comment]
released with ``1.5``
