### ISSUE TITLE
default sepa mandate incompatible with mysql8 

### ISSUE THREAD

**Issue by tttp** [Project60/org.project60.sepa#608]
@bjendres , just wanted to flag @rthouvenin finding:

MySQL 8 changed the default auto-increment mode from "consecutive" to "interleave": https://dev.mysql.com/doc/refman/8.0/en/innodb-auto-increment-handling.html

This has various benefits in terms of performance, locking and reliability, but I think as a result the next auto-increment value is not always written to disk.
The documentation of the auto_increment column does not say anything about it: https://dev.mysql.com/doc/refman/8.0/en/information-schema-tables-table.html

so the way civisepa generates new mandates:

SELECT auto_increment FROM information_schema.tables WHERE ... table_name='civicrm_sdd_mandate';

means that we can (and did) end up with new mandate reference being already used.

More investigation and hopefully fix coming, just wanted to flag a problem after our upgrade to mysql8

**Comment by bjendres** [comment]
A assume closed in favour of #609

**Comment by tttp** [comment]
yeah, 609 is the right one indeed.
