### ISSUE TITLE
Performance issues with CiviCRM 5.36 - 5.40.1

### ISSUE THREAD

**Issue by bjendres** [Project60/org.project60.sepa#614]
When creating a large number of contributions by using the "update RCUR" button on the dashboard, there might be some serious performance issues with the CiviCRM versions ``5.36`` through ``5.40.1`` when using campaigns.

Thanks to @pfigel for hunting this down, providing a CiviCRM patch, and giving us a heads up. See [CORE-2743](https://lab.civicrm.org/dev/core/-/issues/2743).

**Comment by jensschuppe** [comment]
Closing due to affected CiviCRM Core versions being quite old now.
