### ISSUE TITLE
Heads up for 5.43 - CRM_Core_EntityReference removed

### ISSUE THREAD

**Issue by demeritcowboy** [Project60/org.project60.sepa#616]
The DAO's here will need regenerating.

https://github.com/civicrm/civicrm-core/pull/21408, specifically: https://github.com/civicrm/civicrm-core/pull/21408/files#diff-8a528a93562f16025550d7368cb5761898c7159e2310696dd9c25d95610c6704

**Comment by bjendres** [comment]
thanks @demeritcowboy !

**Comment by Detsieber** [comment]
This is important, in fact, because after updating to 5.43 some functionality (e.g. deduplication) is not working anymore (WSOD), when CiviSEPA is activated.

Workaround: de-activate CivSEPA. Which is not a good solution.

**Comment by Detsieber** [comment]
The issue is solved with 1.6-alpha2 
Thanks a lot, Björn.
