### ISSUE TITLE
Deferring collection date after weekend not sufficient

### ISSUE THREAD

**Issue by Detsieber** [Project60/org.project60.sepa#619]
When the option "exclude_weekends" is selected, the collection date will be deferred to Monday, in case it would be on Saturday or Sunday.

However, this won't be sufficient in many cases:

Typically, the rules of several banks are as follows: 
- If the SEPA file is uploaded until 14:00h, the collection can happen the following day (means: CiviSEPA should be set up to defer the collection by 1 day)
- If the SEPA file is uploaded after 14:00h (which will happen typically if the process is done by volunteers after their regular working hours!), the collection has to be deferred by 2 days.

If in the latter case, the SEPA file gets uploaded on Friday afternoon (or Saturday), the collection date will be calculated by CiviSEPA to Monday. However, the bank will not accept this file, because they cannot collect earlier than Tuesday.

**Possible solution:**
There should be another setting besides the "exclude weekends": There one should be able to enter the number of extra_defer_days after a weekend (in this case: 1).

**Comment by bjendres** [comment]
You can implement such an algorithm using the ``civicrm_defer_collection_date`` hook, see [HERE](https://github.com/Project60/org.project60.sepa/blob/1.6-alpha2/org.project60.sepacustom/sepacustom.php#L131-L146). 

That being said, it would be nice to have a reference implementation with configuration options for what you're describing, so anyone can use it. However, I would place this rather in a companion extension like [de.systopia.sepacustom](https://github.com/systopia/de.systopia.sepacustom) than in the CiviSEPA core.

**Comment by pminf** [comment]
Hey @Detsieber, we have the same requirement and would like the collection date to be deferred to Tuesday, if the collection was submitted on a Friday. Have you used the mentioned hook to solve this? I would be grateful if you could share your solution here.

**Comment by Detsieber** [comment]
Hi @pminf unfortunately, we haven't yet implemented this ... Making the calculation of the deferral "waterproof" was not so easy at first... and I did not give enough priority for that until now.
