### ISSUE TITLE
Can't add a SEPA contribution with SEPA 1.5 on CiviCRM 5.44

### ISSUE THREAD

**Issue by allinappli** [Project60/org.project60.sepa#626]
Deprecated: Array and string offset access syntax with curly braces is deprecated in /home/allingro/testwpcivi/wp-content/uploads/civicrm/ext/org.project60.sepapp-master/sepapp.civix.php on line 260

This happens when trying to add a payment through 'SEPA mandate' tab. And we don't have the button event though everything seems set according to the documentation.

![image](https://user-images.githubusercontent.com/62597730/151840314-5b0b63f2-64a0-488a-b292-b4d3ff723791.png)

When creating with the 'Action' menu, it also doesn't appear even though it is recorded

![image](https://user-images.githubusercontent.com/62597730/151840534-0a2d4074-74a4-47ee-9629-bba914ae52a6.png)

It does actually appear in Contribution > Recurring Contribution

![image](https://user-images.githubusercontent.com/62597730/151840846-c77bfe1d-91bc-4043-856b-28be0bff5316.png)

**Comment by bjendres** [comment]
Thanks for reporting, @allinappli. First, a heads up: CiviSEPA 1.5 isn't compatible with CiviCRM 5.44, see #161. We're trying to get 1.6 out soon.

With respect to the other things:

> Deprecated: Array and string offset access syntax with curly braces is deprecated in /home/allingro/testwpcivi/wp-content/uploads/civicrm/ext/org.project60.sepapp-master/sepapp.civix.php on line 260

This refers to the companion extension, https://github.com/Project60/org.project60.sepapp. Maybe that one needs updating, too? If you can still reproduce the "deprecated" warning, please file there.

> This happens when trying to add a payment through 'SEPA mandate' tab. And we don't have the button event though everything seems set according to the documentation.

That sounds weird to me, but it's hard to debug from here. Did you grant all the SEPA permissions to the user you're working with?

**Comment by allinappli** [comment]
Hi! @bjendres I hadn't seen the limitation with 5.44 (but not sure the #161 explains why). 

We'll try the 1.6 alpha2 version and report directly into sepapp project if still needed. We're using version 1.0 which seems to be the last and most recent one and our user has administrator permissions.

I'll let you know how it works

**Comment by allinappli** [comment]
trying with 1.6 alpha2 and companion extension app version 1.1dev (from the same zip folder) leads to the same situation on 5.44.

there's no button added to the contribution tab.

We can still create a SEPA mandate from the `action` menu, the operation seems to be recorded and is inaccessible

![image](https://user-images.githubusercontent.com/62597730/151962140-f154d4f5-1f4a-4e16-bac5-aa483a69e3b4.png)

Clicking on `SEPA Mandates` shows a server error not recorded in the console

**Comment by bjendres** [comment]
> trying with 1.6 alpha2 and companion extension app version 1.1dev leads to the same situation on 5.44.

Again, it looks like your problem is coming from ``org.project60.sepapp-master/sepapp.civix.php``, which is [THIS](https://github.com/Project60/org.project60.sepapp) extension. If you update to latest ``master`` of *that* extension, the error should go away. If not, please open a ticket there.
