### ISSUE TITLE
Offer two versions of format ``pain_008_001_02_OTHERID``

### ISSUE THREAD

**Issue by bjendres** [Project60/org.project60.sepa#627]
Offer two versions of format ``pain_008_001_02_OTHERID``, one with and one without ``Nm`` tag. See #589, #624 and #623.

**Comment by bjendres** [comment]
I have created (and attached) ``1.6-dev+42abf3e27`` (attached) with a the new format ``pain.008.001.02 without BIC and Debitor Name``. 

@Detsieber please test and confirm that it works as soon as possible, I'd like to get ``1.6`` out as soon as possible.

[org.project60.sepa-1.6-dev+42abf3e27.tar.gz](https://github.com/Project60/org.project60.sepa/files/8069689/org.project60.sepa-1.6-dev%2B42abf3e27.tar.gz)

**Comment by Detsieber** [comment]
Hi Björn,

the change you made within 
pain_008_001_02_NODBTRNM/transaction-details.tpl  is not working!!

The change I proposed to pain_008_001_02_OTHERID/transaction-details.tpl 
was simply, to remove line 32.

Instead you removed a totally differen Nm-Tag in line 64...

Could you please update that?


Best
Detlev

**Comment by bjendres** [comment]
I've changed that, and created ``org.project60.sepa-1.6-dev+6c99ef9d45`` (attached). Please test.
[org.project60.sepa-1.6-dev+6c99ef9d45.tar.gz](https://github.com/Project60/org.project60.sepa/files/8078231/org.project60.sepa-1.6-dev%2B6c99ef9d45.tar.gz).

**Comment by bjendres** [comment]
You might have to update the file format for your creditor again.

**Comment by bjendres** [comment]
> it's now called "pain.008.001.02 without BIC and Debitor Name"

I'm actually going to rename this to "pain.008.001.02 without BIC and CdtrSchmId:Nm"

**Comment by bjendres** [comment]
> I tested and it works well now!

Great, thanks. Will be released with ``1.6``
