### ISSUE TITLE
 Self-Healing Mandates (After update to 1.6 recurring contributions are created with wrong payment_instrument_id and other issues)

### ISSUE THREAD

**Issue by Matt5K** [Project60/org.project60.sepa#629]
After an update to version 1.6 each time recurring contributions are updated via the dashboard new contributions are created for recurring mandates even if there is a contribution for the current period. All these contributions have the payment_instrument_id set for the first recurring payment.

**Comment by bjendres** [comment]
Thanks @Matt5K, we've just noticed that as well and are looking into this.

**Comment by bjendres** [comment]
I'm assuming that this might have to do with slightly incorrect mandates / recurring contributions created by payment processors. Does that make sense?

I have added a "self-healing" feature to CiviSEPA that is executed when batching (attached). Feel free to test, but please make a backup or use a test environment. It would also make sense to clean up open groups and delete old, orphaned pending CiviSEPA contributions. Here's the file: [org.project60.sepa-1.6.0+f543fdf6bef7.zip](https://github.com/Project60/org.project60.sepa/files/8381075/org.project60.sepa-1.6.0%2Bf543fdf6bef7.zip)

Can you confirm that this would solve your problem?
.

**Comment by bjendres** [comment]
@Detsieber thanks for the feedback. Have you tested the "self-healing" version mentioned above? Could you give some feedback on that?

**Comment by Detsieber** [comment]
@bjendres yes, I was testing with the "self healing" version you provided!

**Comment by bjendres** [comment]
Sounds like we'll have to add another algorithm to the "self healing" process.

**Comment by bjendres** [comment]
> yes, I was testing with the "self healing" version you provided!

@Detsieber The "self-healing" is currently only triggered when batching. So the idea would be to delete all open groups along with the contributions and then run the batching. Have you done that? If your problem still remains, could provide some data sample or access to your DB to see what exactly is wrong?

**Comment by bjendres** [comment]
I've added another self-healing processor with the attached version. If that doesn't fix your issue, I would have to have a closer look at your system.

[org.project60.sepa-1.6.0+3391594c10.tar.gz](https://github.com/Project60/org.project60.sepa/files/8425058/org.project60.sepa-1.6.0%2B3391594c10.tar.gz)
.

**Comment by bjendres** [comment]
released with ``1.6.1``
