### ISSUE TITLE
Tab "SEPA Mandate" shows when no permission is given

### ISSUE THREAD

**Issue by mariav0** [Project60/org.project60.sepa#635]
I have noticed that the Tab "SEPA Mandate" including all information is shown for users who do/should not have this permission.
Tested on CiviCRM 5.47.4 and earlier versions.
SEPA v. 1.6.0

**Comment by bjendres** [comment]
@mariav0 Could you verify that the patch above works for you?

**Comment by mariav0** [comment]
@bjendres Yes, it works, thanks!

**Comment by bjendres** [comment]
merged, will be in released in ``1.8``

**Comment by bjendres** [comment]
released with ``1.8.0``
