### ISSUE TITLE
PHP 8.0 Compatibility

### ISSUE THREAD

**Issue by bjendres** [Project60/org.project60.sepa#645]

**Comment by bjendres** [comment]
Ping @bbaermann

**Comment by bjendres** [comment]
For CI to be working we need https://github.com/michaelmcandrew/civicrm-buildkit-docker/issues/71

**Comment by eptbertram** [comment]
CiviSEPA is working with PHP 8.1.11 under CiviCRM 5.53.0 WordPress Version 6.0.3. Great! 
But sepapp isn't: https://github.com/Project60/org.project60.sepapp/issues/14

**Comment by bjendres** [comment]
released with ``1.8.0``
