### ISSUE TITLE
Localise more strings

### ISSUE THREAD

**Issue by bjendres** [Project60/org.project60.sepa#647]
Some strings seem to have evaded translation:

- "Installs"
- "every 1 month"
- "Send receipt for each contribution?"
- "No contributions have been recorded for this recurring contribution."
- (probably more...)

**Comment by eptbertram** [comment]
> This is not a correct IBAN. This is not a correct BIC.
> 
> These are front end strings. I can't find them in code :(
> 
> https://github.com/Project60/org.project60.sepa/blob/master/l10n/de_DE/LC_MESSAGES/sepa.po#L3821 seems to be a back end string.

Front end, indeed: This is from [#: CRM/Core/Payment/SDD.php CRM/Core/Payment/SDDNG.php ](https://github.com/Project60/org.project60.sepapp/blob/8ec829939220ccf477e24a3f7416193941537448/l10n/org.project60.sepapp.pot#L30) and not sepa. 

Sorry for confusion.

**Comment by bjendres** [comment]
Yes, sorry, this is not part of the CiviSEPA Extension any more, but has been migrated into the SEPA payment processor extensions:

1. https://github.com/Project60/org.project60.sepapp
2. https://github.com/systopia/de.systopia.sddpp

(both of which are somewhat shaky, as the concept of a payment processor doesn't really fit the SEPA workflow)
