### ISSUE TITLE
CI Tests Fail

### ISSUE THREAD

**Issue by bjendres** [Project60/org.project60.sepa#648]
Out of nowhere, the CI fails with "This mandate has no contribution, even though there should be one", see [HERE](https://app.circleci.com/pipelines/github/Project60/org.project60.sepa/265/workflows/c259318c-0a75-457b-9a01-339057217982/jobs/740/tests#failed-test-0)

**Comment by bjendres** [comment]
This seems to have been fixed with [#632]

**Comment by jensschuppe** [comment]
@bjendres Can we delete the branch `issue/648`? It has three commits that fiddle with the CircleCI config and has not been merged.
