### ISSUE TITLE
Upgrade broken vor v1.8: Download failed - ZIP file is unavailable or malformed

### ISSUE THREAD

**Issue by bastienho** [Project60/org.project60.sepa#661]
Hi

When I want to upgrade SEPA Direct Debit from v1.6 to 1.8, I follow the basic steps:

## 1. Click on upgrade
![image](https://user-images.githubusercontent.com/2409849/224741795-a8c1f9d7-8f83-42c4-bab5-490ac48ed4a3.png)

## 2. Check upgrade
Take care about the file extension
```
https://github.com/Project60/org.project60.sepa/releases/download/1.8.0/org.project60.sepa-1.8.0.tar.gz
```
![image](https://user-images.githubusercontent.com/2409849/224741838-81611c23-a1ec-4eac-81d7-6d30da9ed22b.png)

## 3. Get an error
Here, We can see that the expected file is a `.zip` format.
![image](https://user-images.githubusercontent.com/2409849/224742533-780b9971-ce2e-407a-b887-96d558f0cfa1.png)

Anybody figured the same?

**Comment by bjendres** [comment]
Yes, that was me, sorry.

I wasn't aware that the upgrade cannot deal with tarballs. I adjusted the link in the [extension record](https://civicrm.org/extensions/civisepa-sepa-direct-debit-extension), but it might take a while to take effect in the frontend.

@bastienho Could you try again and let me know how it went?

**Comment by bastienho** [comment]
It worked!

Thank you for your quick intervention.

**Comment by bjendres** [comment]
> It worked! Thank you for your quick intervention.

Great. Thanks for reporting!
