### ISSUE TITLE
BIC is required in Actions to create Recurring or One Off but should respect the setting uses BIC for the account

### ISSUE THREAD

**Issue by ErikHommel** [Project60/org.project60.sepa#681]
At the moment the BIC is a required parameters in the Actions CreateOneOffMandate and CreateRecurringMandate. This does not respect the setting of the account, where uses BIC can be switched off. Should be changed to respect the setting.

**Comment by bjendres** [comment]
Yes, it looks like this scenario was not considered in the implementation.

@ErikHommel Will you be working on this, or "just" reporting?
