### ISSUE TITLE
Is membership update now working?

### ISSUE THREAD

**Issue by allinappliadmin** [Project60/org.project60.sepa#692]
In the documentation I can read that the extension can't yet handle membership payments (which is my issue)
![image](https://github.com/Project60/org.project60.sepa/assets/62597730/2bbecc36-bb62-4c60-9f76-7bb6cae86f57)

but in the release notes, I don't read it any more even though I still have the issue.
![image](https://github.com/Project60/org.project60.sepa/assets/62597730/8dcf60be-6f9d-4248-ab5e-d65dcade4247)

Is it now possible or not to update membership status when the batch is closed with version 1.10.dev?

**Comment by bjendres** [comment]
Not out of the box, no. At least as far as I know.

You could use another extension to achieve this, though. One example would be the https://github.com/project60/org.project60.membership extension, but I think there might be other options out there.
