### ISSUE TITLE
Missing Direct Debit Agreement with payment processor type "SEPA Direct Debit (NEW)"

### ISSUE THREAD

**Issue by romymy** [Project60/org.project60.sepa#695]
Some time ago a very old bug in CiviCRM Core was fixed (I think there were, strictly speaking, several errors). Before these fixes the SEPA agreement was ALWAYS displayed in e.g. contribution forms, regardless of whether the direct debit payment method was selected or not ([#4204](https://lab.civicrm.org/dev/core/-/issues/4204) and [#4189](https://lab.civicrm.org/dev/core/-/issues/4189)).

The bug fixes have now resulted in the agreement no longer appearing in some forms. I looked into this and it turns out that it depends on which “Payment Processor Type” is used when configuring a payment processor. With “SEPA Direct Debit” everything is fine, with “SEPA Direct Debit (NEW)” the agreement is not displayed. Unfortunately I haven't figured out why yet ... so I don't know if it's a Core-Issue or placed correctly here.

**Comment by bjendres** [comment]
Thanks for reporting, @romymy! 

I'm fairly sure that this issue should be raised in the [SEPA Payment Processor extension](https://github.com/Project60/org.project60.sepapp), could you do that please? Feel free to re-open if you disagree.

**Comment by romymy** [comment]
Oh sorry, I just created the Issue [here.](https://github.com/Project60/org.project60.sepapp/issues/23)

**Comment by bjendres** [comment]
> Oh sorry, I just created the Issue [here.](https://github.com/Project60/org.project60.sepapp/issues/23)

Thanks! And no need to be sorry, I know it's confusing.
