### ISSUE TITLE
Support IBAN-only payments

### ISSUE THREAD

**Issue by Detsieber** [Project60/org.project60.sepa#95]
BIC won't be mandatory anymore for domestic payments in some countries (including Germany) as of February 2014.

Required changes:
1) Allow omitting BIC when IBAN begins with "DE" (and maybe some other rules...). 
2) Change xml file:
        <DbtrAgt>
          <FinInstnId>
            <Othr><Id>NOTPROVIDED</Id></Othr>
          </FinInstnId>
        </DbtrAgt>

**Comment by tttp** [comment]
Hi @Detsieber,

Did you look what are the countries that do not need the BIC anymore?

I'm not clear about the XML file, is this supposed to be with without the <bic> tag or with bic tag = NOTPROVIDED?

**Comment by DanielvV** [comment]
**Looks like most sepa country don't need BIC anymore**

> The BIC is only mandatory when the Creditor
> Bank is located in a non-EEA SEPA country or
> territory.

non-EAA SEPA countries (deduced from [1](https://www.gov.uk/eu-eea) and [2](https://www.europeanpaymentscouncil.eu/sites/default/files/KB/files/EPC064-16%20Map%20of%20SEPA%20countries%20and%20territories.pdf)):
Monaco
San Marino
Switzerland
Not sure about some other islands or oversees countries listed under the [second link](https://www.europeanpaymentscouncil.eu/sites/default/files/KB/files/EPC064-16%20Map%20of%20SEPA%20countries%20and%20territories.pdf).

_Source: page 18 in [EPC130-08 SDD Core C2B IG 2017 V1.0.pdf](https://www.europeanpaymentscouncil.eu/sites/default/files/KB/files/EPC130-08%20SDD%20Core%20C2B%20IG%202017%20V1.0.pdf) on the [epc-cep](https://www.europeanpaymentscouncil.eu/document-library/implementation-guidelines/sepa-direct-debit-core-scheme-customer-bank) website_


**And the bic tag is not needed (neither for creditor nor debitor)**

> <xs:element maxOccurs="1" minOccurs="0" name="BICFI" type="BICFIIdentifier"/>

> <xs:element maxOccurs="1" minOccurs="0" name="AnyBIC" type="AnyBICIdentifier"/>

_Source: schema [pain.008.001.07](https://www.iso20022.org/sites/default/files/documents/messages/pain/schemas/pain.008.001.07.xsd) on  the [iso20022](https://www.iso20022.org/payments_messages.page) website._

**Comment by systopia** [comment]
I had started working on this (see https://github.com/systopia/org.project60.sepa/tree/dev_95) but then the client backed out. If there is funding, I'll be happy to complete this - especially if somebody could help with the testing....

**Comment by tttp** [comment]
Hi,
On our side, we did a "brutal" test: simply put a "NOTPROVIDED" in the xml (ie. ignoring the real BIC)
and it works. We might loose donations from monaco or san marino, so be it ;)

Seriously, I'm keeping an eye on it, but it works fine it seems

**Comment by bjendres** [comment]
implemented with #245
